Document of c-modernization-kit (override-sample): override-sample/libsrc/base/DllMain.c File Reference
DllMain.c File Reference
base.so / base.dll のアンロード時処理。
#include "libbase_local.h"
#include <stddef.h>
#include <syslog.h>
Macros
#define LOG_INFO_MSG(msg)
Functions
static void onUnload (void)
__attribute__ ((destructor))
共有ライブラリアンロード時のデストラクタ (Linux 専用)。
Detailed Description
base.so / base.dll のアンロード時処理。
Author
c-modenization-kit sample team
Date
2026/02/21
Version
1.0.0
base.so / base.dll がアンロードされるとき、func.c がキャッシュした liboverride のハンドルと関数ポインタを解放します。
Linux : attribute((destructor)) により dlclose(base.so) または プロセス正常終了時に自動的に呼び出されます。
Windows: DllMain の DLL_PROCESS_DETACH により FreeLibrary(base.dll) または プロセス正常終了時に自動的に呼び出されます。
Copyright
Copyright (C) CompanyName, Ltd. 2026. All rights reserved.
Definition in file DllMain.c.
Macro Definition Documentation
LOG_INFO_MSG
#define LOG_INFO_MSG (msg)
Value:
syslog(LOG_INFO, (msg))
Definition at line 29 of file DllMain.c.
Referenced by onUnload().
Function Documentation
__attribute__()
__attribute__ ((destructor))
共有ライブラリアンロード時のデストラクタ (Linux 専用)。
attribute((destructor)) により、dlclose(base.so) または プロセス正常終了時に自動的に呼び出されます。
Definition at line 49 of file DllMain.c.
References onUnload().
onUnload()
void onUnload (void) static
Definition at line 36 of file DllMain.c.
References libbase_unload_all(), and LOG_INFO_MSG.
Referenced by __attribute__().