Document of c-modernization-kit (override-sample): override-sample/libsrc/base/dllmain_libbase.c File Reference
dllmain_libbase.c File Reference
base.so / base.dll のロード・アンロード時処理。
#include "funcman_libbase.h"
#include <dllmain.h>
#include <stdio.h>
Functions
void onLoad (void)
ライブラリのロード時に呼び出されるフック関数。
void onUnload (void)
ライブラリのアンロード時に呼び出されるフック関数。
Detailed Description
base.so / base.dll のロード・アンロード時処理。
Author
c-modenization-kit sample team
Date
2026/02/21
Version
1.0.0
base.so / base.dll のロード時およびアンロード時に処理を行います。
プラットフォームごとのフック (Linux constructor/destructor, Windows DllMain) は dllmain.h が提供します。このファイルは onLoad / onUnload を定義します。
Copyright
Copyright (C) CompanyName, Ltd. 2026. All rights reserved.
Definition in file dllmain_libbase.c.
Function Documentation
onLoad()
void onLoad (void)
ライブラリのロード時に呼び出されるフック関数。
このヘッダーをインクルードする .c ファイルで定義する必要があります。
Linux では dlopen() またはプロセス起動時に、 Windows では LoadLibrary() またはプロセス起動時に呼び出されます。
Definition at line 24 of file dllmain_libbase.c.
References DLLMAIN_INFO_MSG, fobj_array_libbase, fobj_length_libbase, funcman_configpath, funcman_init(), FUNCMAN_NAME_MAX, get_lib_basename(), and onLoad().
Referenced by __attribute__(), and onLoad().
onUnload()
void onUnload (void)
ライブラリのアンロード時に呼び出されるフック関数。
このヘッダーをインクルードする .c ファイルで定義する必要があります。
Linux では dlclose() またはプロセス正常終了時に、 Windows では FreeLibrary() またはプロセス正常終了時に呼び出されます。
Definition at line 57 of file dllmain_libbase.c.
References DLLMAIN_INFO_MSG, fobj_array_libbase, fobj_length_libbase, and funcman_dispose().
Referenced by __attribute__().