Document of c-modernization-kit (override-sample): override-sample/libsrc/base/lib_loader.c File Reference
lib_loader.c File Reference
動的ライブラリロード Factory 関数の実装ファイル。
#include "libbase_local.h"
#include <stddef.h>
#include <string.h>
Macros
#define LIBBASE_MAX_LIB_NAME 256
Functions
static void libbase_unload_func (LibFuncCache *cache)
void * libbase_load_func_impl (LibFuncCache *cache)
void libbase_unload_all (void)
Variables
LibFuncCache s_cache_func_override
static LibFuncCache *const s_all_caches []
Detailed Description
動的ライブラリロード Factory 関数の実装ファイル。
Author
c-modenization-kit sample team
Date
2026/02/22
Version
1.0.0
ライブラリ名・関数名・ハンドル・関数ポインタを保持する LibFuncCache 構造体に対して、 プラットフォーム共通のロード／アンロード処理を提供します。
libbase_load_func はスレッドセーフです。 内部で mutex (Linux) または SRW ロック (Windows) を使用して排他制御します。 呼び出し元での pthread_once / INIT_ONCE による保護は不要です。
Copyright
Copyright (C) CompanyName, Ltd. 2026. All rights reserved.
Definition in file lib_loader.c.
Macro Definition Documentation
LIBBASE_MAX_LIB_NAME
#define LIBBASE_MAX_LIB_NAME 256
ライブラリ名バッファの最大長 (ベース名 + 拡張子を含む)
Definition at line 26 of file lib_loader.c.
Referenced by libbase_load_func_impl().
Function Documentation
libbase_load_func_impl()
void * libbase_load_func_impl (LibFuncCache * cache)
未ロードなら lib_name に拡張子を付加して dlopen/dlsym し、cache に格納する。 既にロード済みの場合は即座に格納済みの関数ポインタを返す。 内部でロックを取得するためスレッドセーフ。
Returns
成功時 void * (関数ポインタ)、失敗時 NULL
Definition at line 49 of file lib_loader.c.
References LibFuncCache::func_name, LibFuncCache::func_ptr, LibFuncCache::handle, LibFuncCache::lib_name, LIBBASE_MAX_LIB_NAME, and LibFuncCache::mutex.
libbase_unload_all()
void libbase_unload_all (void)
管理下にあるすべてのキャッシュエントリを解放する。 必ず、destructor / DllMain コンテキストから呼ぶこと。
Definition at line 123 of file lib_loader.c.
References libbase_unload_func(), and s_all_caches.
Referenced by onUnload().
libbase_unload_func()
void libbase_unload_func (LibFuncCache * cache) static
cache->handle を閉じ、handle と func_ptr を NULL にリセットする。 DllMain / destructor コンテキストからのみ呼ぶこと。
Definition at line 133 of file lib_loader.c.
References LibFuncCache::func_ptr, and LibFuncCache::handle.
Referenced by libbase_unload_all().
Variable Documentation
s_all_caches
LibFuncCache* const s_all_caches[] static
Initial value:
= {
    &s_cache_func_override,
}
Definition at line 37 of file lib_loader.c.
Referenced by libbase_unload_all().
s_cache_func_override
LibFuncCache s_cache_func_override
Initial value:
=
    LIBFUNCCACHE_INIT("liboverride", "func_override", func_override_t)
Definition at line 32 of file lib_loader.c.
Referenced by func().