Document of c-modernization-kit (override-sample): override-sample/include/libbase.h File Reference
libbase.h File Reference
ベースライブラリ (動的リンク用) のヘッダーファイル。
#include <stddef.h>
#include <dlfcn.h>
#include <pthread.h>
Data Structures
struct funcman_object
関数ポインタキャッシュエントリ。
Macros
#define _GNU_SOURCE
#define BASE_API
DLL エクスポート/インポート制御マクロ。
#define WINAPI
Windows 呼び出し規約マクロ。
#define MODULE_HANDLE void *
Linux/Windows 共通のモジュールハンドル型。
#define FUNCMAN_NAME_MAX 256
lib_name / func_name 配列の最大長 (終端 '\0' を含む)。
#define NEW_FUNCMAN_OBJECT(key, type)
funcman_object 静的変数の初期化マクロ。
#define funcman_get_func(fobj, type)
拡張関数ポインタを返します。
Functions
BASE_API int WINAPI sample_func (const int a, const int b, int *result)
計算処理を行います。
BASE_API void WINAPI console_output (const char *format,...)
printf と同じ書式でコンソールに出力します。
BASE_API int WINAPI get_lib_path (char *out_path, const size_t out_path_sz, const void *func_addr)
指定した関数が所属する共有ライブラリ (.so/.dll) の絶対パスを取得します。
BASE_API int WINAPI get_lib_basename (char *out_basename, const size_t out_basename_sz, const void *func_addr)
指定した関数が所属する共有ライブラリ (.so/.dll) の basename (パスなし・拡張子なし) を取得します。
BASE_API void *WINAPI _funcman_get_func (funcman_object *fobj)
拡張関数ポインタを返します。この関数は内部用です。
BASE_API int WINAPI funcman_is_declared_default (const funcman_object *fobj)
funcman_object が明示的デフォルトかどうかを返します。
BASE_API void WINAPI funcman_init (funcman_object *const *fobj_array, const size_t fobj_length, const char *configpath)
funcman_object ポインタ配列を初期化します。
BASE_API void WINAPI funcman_dispose (funcman_object *const *fobj_array, const size_t fobj_length)
funcman_object ポインタ配列を解放します。
BASE_API int WINAPI funcman_info (funcman_object *const *fobj_array, const size_t fobj_length)
funcman_object ポインタ配列の内容を標準出力に表示します。
BASE_API int WINAPI funcman_info_libbase (void)
libbase が管理する funcman_object ポインタ配列の内容を標準出力に表示します。
Detailed Description
ベースライブラリ (動的リンク用) のヘッダーファイル。
Author
c-modenization-kit sample team
Date
2026/02/21
Version
1.0.0
このライブラリは動的ライブラリのオーバーライド機能を示すサンプルです。
Copyright
Copyright (C) CompanyName, Ltd. 2026. All rights reserved.
Definition in file libbase.h.
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 21 of file libbase.h.
BASE_API
#define BASE_API
DLL エクスポート/インポート制御マクロ。
ビルド条件に応じて以下の値を取ります。
条件 値
Linux (非 Windows) (空)
Windows / __INTELLISENSE__ 定義時 (空)
Windows / BASE_STATIC 定義時 (静的リンク) (空)
Windows / BASE_EXPORTS 定義時 (DLL ビルド) __declspec(dllexport)
Windows / BASE_EXPORTS 未定義時 (DLL 利用側) __declspec(dllimport)
Definition at line 58 of file libbase.h.
WINAPI
#define WINAPI
Windows 呼び出し規約マクロ。
Windows 環境では __stdcall 呼び出し規約を指定します。
Linux (非 Windows) 環境では空に展開されます。
既に定義済みの場合は再定義されません。
Definition at line 59 of file libbase.h.
Referenced by console_output(), override_func(), and sample_func().
MODULE_HANDLE
#define MODULE_HANDLE void *
Linux/Windows 共通のモジュールハンドル型。
Definition at line 149 of file libbase.h.
FUNCMAN_NAME_MAX
#define FUNCMAN_NAME_MAX 256
lib_name / func_name 配列の最大長 (終端 '\0' を含む)。
Definition at line 154 of file libbase.h.
Referenced by _funcman_get_func(), funcman_init(), and onLoad().
NEW_FUNCMAN_OBJECT
#define NEW_FUNCMAN_OBJECT (key, type)
Value:
{(key), {0}, {0}, NULL, NULL, 0, 0, PTHREAD_MUTEX_INITIALIZER}
funcman_object 静的変数の初期化マクロ。
Parameters
[in] key この関数インスタンスの識別キー (文字列リテラル)。
[in] type 格納する関数ポインタの型 (例: sample_func_t)。
Definition at line 188 of file libbase.h.
funcman_get_func
#define funcman_get_func (fobj, type)
Value:
((type)_funcman_get_func(fobj))
拡張関数ポインタを返します。
Parameters
[in] fobj funcman_object へのポインタ。
[in] type NEW_FUNCMAN_OBJECT で指定したものと同じ関数ポインタ型。
Definition at line 212 of file libbase.h.
Referenced by sample_func().
Function Documentation
sample_func()
BASE_API int WINAPI sample_func (const int a, const int b, int * result) extern
計算処理を行います。
Parameters
[in] a 第一オペランド。
[in] b 第二オペランド。
[out] result 計算結果を格納するポインタ。
Returns
成功時は 0、失敗時は -1 を返します。
Warning
result が NULL の場合は -1 を返します。
Definition at line 20 of file sample_func.c.
References console_output(), funcman_get_func, pfo_sample_func, and WINAPI.
Referenced by main().
console_output()
BASE_API void WINAPI console_output (const char * format, ...) extern
printf と同じ書式でコンソールに出力します。
Parameters
[in] format printf 互換の書式文字列。
[in] ... 書式文字列に対応する引数。
この関数は printf のラッパーです。
動的ライブラリ内から呼び出し元プロセスのコンソールに出力します。
使用例
console_output("result: %d\n", 42);  // 出力: result: 42
Definition at line 21 of file console_output.c.
References WINAPI.
Referenced by main(), override_func(), and sample_func().
get_lib_path()
BASE_API int WINAPI get_lib_path (char * out_path, const size_t out_path_sz, const void * func_addr) extern
指定した関数が所属する共有ライブラリ (.so/.dll) の絶対パスを取得します。
Parameters
[out] out_path 出力バッファ。
[in] out_path_sz 出力バッファサイズ[byte]。
[in] func_addr 所属モジュールを特定するための関数アドレス。
Returns
関数が成功した場合、0 を返します。失敗した場合は 0 以外を返します。
Definition at line 313 of file get_lib_info.c.
References get_self_path_posix(), and MYLIB_OK.
Referenced by get_lib_basename().
get_lib_basename()
BASE_API int WINAPI get_lib_basename (char * out_basename, const size_t out_basename_sz, const void * func_addr) extern
指定した関数が所属する共有ライブラリ (.so/.dll) の basename (パスなし・拡張子なし) を取得します。
Linux の .so.1.2.3 のようなバージョン付きは ".so." より前を basename とみなします。
Parameters
[out] out_basename 出力バッファ。
[in] out_basename_sz 出力バッファサイズ[byte]。
[in] func_addr 所属モジュールを特定するための関数アドレス。
Returns
関数が成功した場合、0 を返します。失敗した場合は 0 以外を返します。
Definition at line 331 of file get_lib_info.c.
References copy_str(), get_ilename_part(), get_lib_path(), MYLIB_EFAIL, MYLIB_EINVAL, MYLIB_OK, and strip_extension_inplace().
Referenced by onLoad().
_funcman_get_func()
BASE_API void *WINAPI _funcman_get_func (funcman_object * fobj) extern
拡張関数ポインタを返します。この関数は内部用です。
既にロード済みの場合は即座に格納済みの関数ポインタを返します。
Parameters
[in,out] fobj funcman_object へのポインタ。
Returns
成功時 void * (関数ポインタ)、失敗時 NULL。
Definition at line 21 of file funcman_get_func.c.
References funcman_object::func_name, funcman_object::func_ptr, FUNCMAN_NAME_MAX, funcman_object::handle, funcman_object::lib_name, funcman_object::mutex, and funcman_object::resolved.
Referenced by funcman_info(), and funcman_is_declared_default().
funcman_is_declared_default()
BASE_API int WINAPI funcman_is_declared_default (const funcman_object * fobj) extern
funcman_object が明示的デフォルトかどうかを返します。
lib_name と func_name がともに定義ファイルで default に設定されている場合に 1 を返します。
それ以外の場合は 0 を返します。
Parameters
[in] fobj funcman_object へのポインタ。
Returns
明示的デフォルトの場合は 1、それ以外は 0。
Definition at line 17 of file funcman_is_declared_default.c.
References _funcman_get_func(), and funcman_object::resolved.
funcman_init()
BASE_API void WINAPI funcman_init (funcman_object *const * fobj_array, const size_t fobj_length, const char * configpath) extern
funcman_object ポインタ配列を初期化します。
必ず、constructor / DllMain コンテキストから呼ぶようにしてください。
Parameters
[in] fobj_array funcman_object ポインタ配列。
[in] fobj_length 配列の要素数。
[in] configpath 定義ファイルのパス。
Definition at line 37 of file funcman_init.c.
References CONFIG_LINE_MAX, funcman_object::func_key, funcman_object::func_name, FUNCMAN_NAME_MAX, and funcman_object::lib_name.
Referenced by onLoad().
funcman_dispose()
BASE_API void WINAPI funcman_dispose (funcman_object *const * fobj_array, const size_t fobj_length) extern
funcman_object ポインタ配列を解放します。
必ず、destructor / DllMain コンテキストから呼ぶようにしてください。
Parameters
[in] fobj_array funcman_object ポインタ配列。
[in] fobj_length 配列の要素数。
Definition at line 17 of file funcman_dispose.c.
References funcman_object::func_ptr, and funcman_object::handle.
Referenced by onUnload().
funcman_info()
BASE_API int WINAPI funcman_info (funcman_object *const * fobj_array, const size_t fobj_length) extern
funcman_object ポインタ配列の内容を標準出力に表示します。
Parameters
[in] fobj_array funcman_object ポインタ配列。
[in] fobj_length 配列の要素数。
Returns
すべてのエントリが正常に解決されている場合は 0、1 つでも失敗している場合は -1 を返します。
Definition at line 21 of file funcman_info.c.
References _funcman_get_func(), funcman_object::func_key, funcman_object::func_name, funcman_object::func_ptr, funcman_object::handle, funcman_object::lib_name, and funcman_object::resolved.
Referenced by funcman_info_libbase().
funcman_info_libbase()
BASE_API int WINAPI funcman_info_libbase (void) extern
libbase が管理する funcman_object ポインタ配列の内容を標準出力に表示します。
Returns
すべてのエントリが正常に解決されている場合は 0、1 つでも失敗している場合は -1 を返します。
Definition at line 47 of file funcman_libbase.c.
References fobj_array_libbase, fobj_length_libbase, funcman_configpath, and funcman_info().
Referenced by main().