Document of c-modernization-kit (override-sample): override-sample/src/override-sample/override-sample.c File Reference
override-sample.c File Reference
override-sample メインプログラム。
#include <libbase.h>
#include <stdio.h>
Functions
int main (void)
メインエントリポイント。
Detailed Description
override-sample メインプログラム。
Author
c-modenization-kit sample team
Date
2026/02/21
Version
1.0.0
libbase の func を呼び出し、オーバーライド機能を示すサンプルプログラムです。
Copyright
Copyright (C) CompanyName, Ltd. 2026. All rights reserved.
Definition in file override-sample.c.
Function Documentation
main()
int main (void)
メインエントリポイント。
Returns
正常終了時は 0 を返します。
Definition at line 28 of file override-sample.c.
References console_output(), funcman_info_libbase(), and sample_func().