# Windows PoC: calc コマンドのビルド用 Makefile

# ワークスペースのディレクトリ検索
WORKSPACE_FOLDER := $(shell \
    dir=`pwd`; \
    while [ "$$dir" != "/" ]; do \
        if [ -f "$$dir/.workspaceRoot" ]; then \
            cygpath -w "$$dir" 2>/dev/null || echo $$dir; \
            break; \
        fi; \
        dir=$$(dirname $$dir); \
    done \
)

# ディレクトリ設定
OBJDIR := obj
TARGETDIR := .

# OS 判定
ifeq ($(OS),Windows_NT)
    # Windows 環境 (MSVC)
    CC := cl
    LD := link
    OBJEXT := .obj
    EXEEXT := .exe
    CFLAGS := /nologo /W4 /Zi /TC /utf-8 /MD /Fd$(OBJDIR)/calc.pdb /I$(WORKSPACE_FOLDER)/prod/calc/include
    LDFLAGS := /NOLOGO /DEBUG /PDB:$(TARGETDIR)/calc.pdb /INCREMENTAL /ILK:$(OBJDIR)/calc.ilk /LIBPATH:$(WORKSPACE_FOLDER)/prod/calc/lib
    LIBS := calc.lib
else
    # Linux 環境 (GCC)
    CC := gcc
    LD := gcc
    OBJEXT := .o
    EXEEXT :=
    CFLAGS := -Wall -Wextra -g -std=c99 -I$(WORKSPACE_FOLDER)/prod/calc/include
    LDFLAGS := -L$(WORKSPACE_FOLDER)/prod/calc/lib
    LIBS := -lcalc
endif

# ソースファイル
SRCS_C := $(wildcard *.c)

# オブジェクトファイル
OBJS := $(addprefix $(OBJDIR)/, $(notdir $(patsubst %.c, %$(OBJEXT), $(SRCS_C))))

# ターゲット名
TARGET := calc$(EXEEXT)

# ビルドルール
.PHONY: all
all: $(TARGETDIR)/$(TARGET)

ifeq ($(OS),Windows_NT)
    # Windows (MSVC) のビルドルール
$(TARGETDIR)/$(TARGET): $(OBJS) | $(TARGETDIR)
	$(LD) /OUT:$@ $(OBJS) $(LIBS) $(LDFLAGS)

$(OBJDIR)/%$(OBJEXT): %.c | $(OBJDIR)
	$(CC) $(CFLAGS) /c /Fo$@ $<
else
    # Linux (GCC) のビルドルール
$(TARGETDIR)/$(TARGET): $(OBJS) | $(TARGETDIR)
	$(LD) $(LDFLAGS) -o $@ $(OBJS) $(LIBS)

$(OBJDIR)/%$(OBJEXT): %.c | $(OBJDIR)
	$(CC) $(CFLAGS) -c -o $@ $<
endif

# ディレクトリ作成
$(OBJDIR):
	mkdir -p $@

# クリーン
.PHONY: clean
clean:
	rm -rf $(OBJDIR)
	rm -f $(TARGETDIR)/$(TARGET)
ifeq ($(OS),Windows_NT)
	rm -f $(TARGETDIR)/*.pdb
endif
