# テスト関連ライブラリは、すべて静的リンクとする
ifeq ($(OS),Windows_NT)
    # Windows
    CFLAGS   += /DFMTIO_UTIL_STATIC /DTRACE_ETW_UTIL_STATIC /DTRACE_UTIL_STATIC /DTRACE_FILE_UTIL_STATIC /DCONSOLE_UTIL_STATIC
    CXXFLAGS += /DFMTIO_UTIL_STATIC /DTRACE_ETW_UTIL_STATIC /DTRACE_UTIL_STATIC /DTRACE_FILE_UTIL_STATIC /DCONSOLE_UTIL_STATIC
endif
