# テスト関連ライブラリは、すべて静的リンクとする
ifeq ($(OS),Windows_NT)
    # Windows
    CFLAGS   += /DPATH_FORMAT_STATIC /DTRACE_ETW_STATIC /DTRACE_LOGGER_STATIC /DTRACE_FILE_STATIC /DCONSOLE_STATIC
    CXXFLAGS += /DPATH_FORMAT_STATIC /DTRACE_ETW_STATIC /DTRACE_LOGGER_STATIC /DTRACE_FILE_STATIC /DCONSOLE_STATIC
endif
