# テスト関連ライブラリは、すべて静的リンクとする
ifeq ($(OS),Windows_NT)
    # Windows
    CFLAGS   += /DFMTIO_UTIL_STATIC /DETW_UTIL_STATIC /DLOG_UTIL_STATIC
    CXXFLAGS += /DFMTIO_UTIL_STATIC /DETW_UTIL_STATIC /DLOG_UTIL_STATIC
endif
