ifdef PLATFORM_WINDOWS
    # 外部関数の static 定義
    CFLAGS   += /DPATH_FORMAT_STATIC /DTRACE_ETW_STATIC /DTRACE_LOGGER_STATIC /DTRACE_FILE_STATIC /DCONSOLE_STATIC
    CXXFLAGS += /DPATH_FORMAT_STATIC /DTRACE_ETW_STATIC /DTRACE_LOGGER_STATIC /DTRACE_FILE_STATIC /DCONSOLE_STATIC
endif
