ifdef PLATFORM_WINDOWS
    # DLL エクスポート定義
    # DLL export definition
    CFLAGS   += /DPATH_FORMAT_EXPORTS /DTRACE_ETW_EXPORTS /DTRACE_LOGGER_EXPORTS /DTRACE_FILE_EXPORTS /DCONSOLE_EXPORTS /DSYMBOL_LOADER_EXPORTS /DMODULE_INFO_EXPORTS /DCLOCK_EXPORTS /DCOMPRESS_EXPORTS /DCRYPTO_EXPORTS
    CXXFLAGS += /DPATH_FORMAT_EXPORTS /DTRACE_ETW_EXPORTS /DTRACE_LOGGER_EXPORTS /DTRACE_FILE_EXPORTS /DCONSOLE_EXPORTS /DSYMBOL_LOADER_EXPORTS /DMODULE_INFO_EXPORTS /DCLOCK_EXPORTS /DCOMPRESS_EXPORTS /DCRYPTO_EXPORTS
endif

# 生成されるライブラリを動的ライブラリ (shared) とする
# 未指定の場合 (デフォルト) は static
LIB_TYPE = shared
