ifeq ($(OS),Windows_NT)
    # Windows
    # DLL エクスポート定義
    # DLL export definition
    CFLAGS   += /DFMTIO_UTIL_EXPORTS /DTRACE_ETW_UTIL_EXPORTS /DTRACE_UTIL_EXPORTS /DTRACE_FILE_UTIL_EXPORTS /DCONSOLE_UTIL_EXPORTS
    CXXFLAGS += /DFMTIO_UTIL_EXPORTS /DTRACE_ETW_UTIL_EXPORTS /DTRACE_UTIL_EXPORTS /DTRACE_FILE_UTIL_EXPORTS /DCONSOLE_UTIL_EXPORTS
endif

# 生成されるライブラリを動的ライブラリ (shared) とする
# 未指定の場合 (デフォルト) は static
LIB_TYPE = shared
