Document of c-modernization-kit (porter): porter/libsrc/porter/protocol/packet.h File Reference
packet.h File Reference
パケット構築・解析モジュールの内部ヘッダー。
#include <stddef.h>
#include <stdint.h>
#include <porter_type.h>
Functions
int packet_build_data (PotrPacket *packet, uint32_t seq_num, const void *data, size_t len)
データパケットを構築します。
int packet_build_ack (PotrPacket *packet, uint32_t ack_num)
ACK パケットを構築します。
int packet_build_nack (PotrPacket *packet, uint32_t nack_num)
NACK パケットを構築します。
int packet_parse (PotrPacket *packet, const void *buf, size_t buf_len)
受信バイト列をパケット構造体に解析します。
size_t packet_wire_size (const PotrPacket *packet)
パケットのヘッダー + ペイロードの合計バイト数を返します。
Detailed Description
パケット構築・解析モジュールの内部ヘッダー。
Author
c-modernization-kit sample team
Date
2026/03/04
Version
1.0.0
Copyright
Copyright (C) CompanyName, Ltd. 2026. All rights reserved.
Definition in file packet.h.
Function Documentation
packet_build_data()
int packet_build_data (PotrPacket * packet, uint32_t seq_num, const void * data, size_t len) extern
データパケットを構築します。
Parameters
[out] packet 構築結果を格納するパケット構造体へのポインタ。
[in] seq_num 通番。
[in] data ペイロードデータへのポインタ。
[in] len ペイロードのバイト数。
Returns
成功時は POTR_SUCCESS、失敗時は POTR_ERROR を返します。
各フィールドをネットワークバイトオーダーに変換してパケットを構築します。
Definition at line 40 of file packet.c.
References PotrPacket::ack_num, PotrPacket::flags, PotrPacket::payload, PotrPacket::payload_len, POTR_ERROR, POTR_FLAG_DATA, POTR_MAX_PAYLOAD, POTR_SUCCESS, and PotrPacket::seq_num.
Referenced by potrSend().
packet_build_ack()
int packet_build_ack (PotrPacket * packet, uint32_t ack_num) extern
ACK パケットを構築します。
Parameters
[out] packet 構築結果を格納するパケット構造体へのポインタ。
[in] ack_num 確認応答番号。
Returns
成功時は POTR_SUCCESS、失敗時は POTR_ERROR を返します。
Definition at line 66 of file packet.c.
References PotrPacket::ack_num, PotrPacket::flags, PotrPacket::payload_len, POTR_ERROR, POTR_FLAG_ACK, POTR_SUCCESS, and PotrPacket::seq_num.
packet_build_nack()
int packet_build_nack (PotrPacket * packet, uint32_t nack_num) extern
NACK パケットを構築します。
Parameters
[out] packet 構築結果を格納するパケット構造体へのポインタ。
[in] nack_num 再送要求する通番。
Returns
成功時は POTR_SUCCESS、失敗時は POTR_ERROR を返します。
Definition at line 90 of file packet.c.
References PotrPacket::ack_num, PotrPacket::flags, PotrPacket::payload_len, POTR_ERROR, POTR_FLAG_NACK, POTR_SUCCESS, and PotrPacket::seq_num.
Referenced by send_nack().
packet_parse()
int packet_parse (PotrPacket * packet, const void * buf, size_t buf_len) extern
受信バイト列をパケット構造体に解析します。
Parameters
[out] packet 解析結果を格納するパケット構造体へのポインタ。
[in] buf 受信バイト列へのポインタ。
[in] buf_len 受信バイト列の長さ。
Returns
成功時は POTR_SUCCESS、失敗時は POTR_ERROR を返します。
各フィールドをホストバイトオーダーに変換して構造体に格納します。
Definition at line 118 of file packet.c.
References PotrPacket::ack_num, PotrPacket::flags, PotrPacket::payload_len, POTR_ERROR, POTR_MAX_PAYLOAD, POTR_SUCCESS, and PotrPacket::seq_num.
Referenced by recv_thread_func().
packet_wire_size()
size_t packet_wire_size (const PotrPacket * packet) extern
パケットのヘッダー + ペイロードの合計バイト数を返します。
Parameters
[in] packet 対象のパケット構造体へのポインタ。
Returns
パケットの送信サイズ (バイト)。packet が NULL の場合は 0。
UDP 送信時に sendto() へ渡すバイト数を求めるために使用します。
Definition at line 152 of file packet.c.
References PotrPacket::payload_len.
Referenced by potrSend().