Document of c-modernization-kit (porter): porter/include/porter.h File Reference
porter.h File Reference
通信ライブラリ (動的リンク用) のヘッダーファイル。
#include <porter_type.h>
Macros
#define POTR_API
DLL エクスポート/インポート制御マクロ。
#define POTRAPI
Windows 呼び出し規約マクロ。
Functions
POTR_API int POTRAPI potrOpenService (const char *config_path, int service_id, PotrRole role, PotrRecvCallback callback, PotrHandle *handle)
設定ファイルから指定サービスを開きます。
POTR_API int POTRAPI potrSend (PotrHandle handle, const void *data, size_t len, int flags)
メッセージを送信します。
POTR_API int POTRAPI potrCloseService (PotrHandle handle)
サービスを閉じます。
POTR_API int POTRAPI potrLogConfig (PotrLogLevel level, const char *log_file, int console)
ロガーを設定します。
Detailed Description
通信ライブラリ (動的リンク用) のヘッダーファイル。
Author
c-modernization-kit sample team
Date
2026/03/04
Version
1.0.0
このライブラリは UDP/IP を用いたプラットフォーム間通信を提供します。
Linux / Windows クロスプラットフォーム対応の DLL として提供されます。
Copyright
Copyright (C) CompanyName, Ltd. 2026. All rights reserved.
Definition in file porter.h.
Macro Definition Documentation
POTR_API
#define POTR_API
DLL エクスポート/インポート制御マクロ。
ビルド条件に応じて以下の値を取ります。
条件 値
Linux (非 Windows) (空)
Windows / __INTELLISENSE__ 定義時 (空)
Windows / POTR_STATIC 定義時 (静的リンク) (空)
Windows / POTR_EXPORTS 定義時 (DLL ビルド) __declspec(dllexport)
Windows / POTR_EXPORTS 未定義時 (DLL 利用側) __declspec(dllimport)
Definition at line 46 of file porter.h.
Referenced by potrCloseService(), potrLogConfig(), potrOpenService(), and potrSend().
POTRAPI
#define POTRAPI
Windows 呼び出し規約マクロ。
Windows 環境では __stdcall 呼び出し規約を指定します。
Linux (非 Windows) 環境では空に展開されます。
既に定義済みの場合は再定義されません。
Definition at line 47 of file porter.h.
Referenced by potrCloseService(), potrLogConfig(), potrOpenService(), and potrSend().
Function Documentation
potrOpenService()
POTR_API int POTRAPI potrOpenService (const char * config_path, int service_id, PotrRole role, PotrRecvCallback callback, PotrHandle * handle) extern
設定ファイルから指定サービスを開きます。
Parameters
[in] config_path 設定ファイルのパス。
[in] service_id 開くサービスの ID。
[in] role 役割種別。POTR_ROLE_SENDER または POTR_ROLE_RECEIVER。
[in] callback イベント発生時に呼び出されるコールバック関数 (PotrRecvCallback)。 POTR_ROLE_RECEIVER の場合は必須。データ受信・接続検知・切断検知を受け取る。 POTR_ROLE_SENDER の場合は NULL を指定すること。
[out] handle 成功時にセッションハンドルを格納するポインタ。
Returns
成功時は POTR_SUCCESS、失敗時は POTR_ERROR を返します。
設定ファイルを解析してサービス定義を取得し、UDP ソケットを初期化します。
role と callback の組み合わせが不正な場合は POTR_ERROR を返します。
role と設定ファイルの IP アドレスが不整合 (bind 失敗など) の場合も POTR_ERROR を返します。
通信種別・役割に応じて以下のソケット設定を行います。
通信種別 役割 bind アドレス bind ポート
POTR_TYPE_UNICAST 送信者 src_addr src_port
POTR_TYPE_UNICAST 受信者 dst_addr dst_port
POTR_TYPE_MULTICAST 送信者 INADDR_ANY src_port
POTR_TYPE_MULTICAST 受信者 INADDR_ANY dst_port
POTR_TYPE_BROADCAST 送信者 src_addr src_port
POTR_TYPE_BROADCAST 受信者 INADDR_ANY dst_port
POTR_ROLE_RECEIVER の場合、内部で受信スレッドを起動します。
使用例 (受信者)
void on_recv(int service_id, PotrEvent event,
             const void *data, size_t len) {
    if (event == POTR_EVENT_CONNECTED)
        printf("service %d: connected\n", service_id);
    else if (event == POTR_EVENT_DISCONNECTED)
        printf("service %d: disconnected\n", service_id);
    else
        printf("service %d: received %zu bytes\n", service_id, len);
}
PotrHandle handle;
if (potrOpenService("porter-services.conf", 1001,
                    POTR_ROLE_RECEIVER, on_recv, &handle) == POTR_SUCCESS) {
    // 受信待機中 (受信スレッドが動作)
    potrCloseService(handle);
}
使用例 (送信者)
PotrHandle handle;
if (potrOpenService("porter-services.conf", 1001,
                    POTR_ROLE_SENDER, NULL, &handle) == POTR_SUCCESS) {
    potrSend(handle, "hello", 5, 0);
    potrCloseService(handle);
}
Warning
handle が NULL の場合は失敗を返します。
config_path が NULL または存在しない場合は失敗を返します。
指定した service_id が設定ファイルに存在しない場合は失敗を返します。
POTR_ROLE_RECEIVER かつ callback が NULL の場合は失敗を返します。
POTR_ROLE_SENDER かつ callback が NULL でない場合は失敗を返します。
Definition at line 305 of file potrOpenService.c.
References PotrServiceDef::broadcast_addr, PotrContext_::callback, comm_recv_thread_start(), PotrContext_::compress_buf, PotrContext_::compress_buf_size, config_load_global(), config_load_service(), PotrContext_::crypto_buf, PotrContext_::crypto_buf_size, ctx_cleanup(), PotrContext_::dest_addr, PotrServiceDef::dst_addr, PotrContext_::dst_addr_resolved, PotrServiceDef::dst_port, PotrServiceDef::encrypt_enabled, PotrContext_::frag_buf, generate_session(), PotrContext_::global, PotrGlobalConfig::health_interval_ms, PotrGlobalConfig::health_timeout_ms, PotrGlobalConfig::max_message_size, PotrGlobalConfig::max_payload, PotrServiceDef::multicast_group, PotrContext_::n_path, open_socket_broadcast(), open_socket_multicast(), open_socket_unicast(), PACKET_HEADER_SIZE, parse_ipv4_addr(), POTR_API, POTR_COMPRESS_HEADER_SIZE, POTR_CRYPTO_TAG_SIZE, POTR_ERROR, potr_health_thread_start(), potr_health_thread_stop(), POTR_INVALID_SOCKET, POTR_LOG, POTR_LOG_DEBUG, POTR_LOG_ERROR, POTR_LOG_INFO, POTR_MAX_PATH, POTR_MAX_PAYLOAD, POTR_MAX_WINDOW_SIZE, POTR_ROLE_RECEIVER, POTR_ROLE_SENDER, potr_send_queue_destroy(), potr_send_queue_init(), potr_send_thread_start(), potr_send_thread_stop(), POTR_SUCCESS, POTR_TYPE_BROADCAST, POTR_TYPE_MULTICAST, POTR_TYPE_UNICAST, POTRAPI, PotrContext_::recv_buf, PotrContext_::recv_window, resolve_ipv4_addr(), PotrContext_::role, PotrContext_::send_queue, PotrGlobalConfig::send_queue_depth, PotrContext_::send_window, PotrContext_::send_wire_buf, PotrContext_::service, PotrContext_::sock, PotrServiceDef::src_addr, PotrContext_::src_addr_resolved, PotrServiceDef::src_port, PotrServiceDef::type, window_init(), and PotrGlobalConfig::window_size.
Referenced by main().
potrSend()
POTR_API int POTRAPI potrSend (PotrHandle handle, const void * data, size_t len, int flags) extern
メッセージを送信します。
Parameters
[in] handle potrOpenService() で取得したセッションハンドル。
[in] data 送信するメッセージへのポインタ。
[in] len 送信するメッセージのバイト数。
[in] flags 送信オプションフラグ。以下のフラグを論理和で組み合わせて指定します。 0 を指定すると非圧縮・ノンブロッキング送信になります。
フラグ 説明
POTR_SEND_COMPRESS メッセージを圧縮して送信します。
POTR_SEND_BLOCKING ブロッキング送信を行います。
Returns
成功時は POTR_SUCCESS、失敗時は POTR_ERROR を返します。
通信種別に応じて以下の宛先へ UDP パケットを送信します。
通信種別 送信先
POTR_TYPE_UNICAST 接続相手の dst_port 宛にユニキャスト送信
POTR_TYPE_MULTICAST multicast_group:dst_port へ送信
POTR_TYPE_BROADCAST broadcast_addr:dst_port へ送信
compress に POTR_SEND_COMPRESS を指定した場合、内部で圧縮処理を行ってから送信します。
圧縮後のサイズが元のサイズ以上になった場合は、自動的に非圧縮で送信します。
受信側の PotrRecvCallback には、解凍済みの元メッセージが渡されます。
送受信ともにフラグメント化と組み合わせて使用できます。
ノンブロッキング送信 (flags に POTR_SEND_BLOCKING を指定しない場合)
メッセージを内部送信キューに登録して即座に返ります。
実際の sendto はバックグラウンド送信スレッドが非同期に実行します。
キューが満杯の場合は空きが生じるまで待機してからメッセージを登録し、登録後に返ります。
ブロッキング送信 (flags に POTR_SEND_BLOCKING を指定した場合)
呼び出し前に滞留しているノンブロッキング送信のメッセージが すべて sendto 完了するまで待機します。
その後、本呼び出しのメッセージをキューを通じて sendto して返ります。
本関数が返った時点で、自身のメッセージの sendto は完了しています。
Note
圧縮フォーマットには raw DEFLATE (RFC 1951) を使用します。
Linux (zlib) と Windows (Compression API MSZIP|COMPRESS_RAW) は 同一フォーマットを出力するため、クロスプラットフォーム通信に対応します。
圧縮効果がない場合 (圧縮後サイズ >= 元サイズ) は、アプリケーションへの通知なしに 内部で非圧縮に切り替えて送信します。送受信のデータ内容に影響はありません。
本関数はシングルスレッドから呼び出すことを前提としています。 複数スレッドから同時に呼び出した場合の動作は未定義です。
Warning
handle が NULL の場合は失敗を返します。
data が NULL の場合は失敗を返します。
len が 0 の場合は失敗を返します。
len が POTR_MAX_MESSAGE_SIZE を超える場合は失敗を返します。
送信スレッドが停止している場合 (potrCloseService 呼び出し後など) は失敗を返します。
Definition at line 23 of file potrSend.c.
References PotrContext_::compress_buf, PotrContext_::compress_buf_size, PotrServiceDef::encrypt_enabled, PotrContext_::global, PotrGlobalConfig::max_message_size, PotrGlobalConfig::max_payload, POTR_API, potr_compress(), POTR_CRYPTO_TAG_SIZE, POTR_ERROR, POTR_FLAG_COMPRESSED, POTR_FLAG_MORE_FRAG, POTR_LOG, POTR_LOG_ERROR, POTR_LOG_TRACE, POTR_PAYLOAD_ELEM_HDR_SIZE, POTR_SEND_BLOCKING, POTR_SEND_COMPRESS, potr_send_queue_push_wait(), potr_send_queue_wait_drained(), POTR_SUCCESS, POTRAPI, PotrContext_::send_queue, PotrContext_::send_thread_running, PotrContext_::service, and PotrServiceDef::service_id.
Referenced by main().
potrCloseService()
POTR_API int POTRAPI potrCloseService (PotrHandle handle) extern
サービスを閉じます。
Parameters
[in] handle potrOpenService() で取得したセッションハンドル。
Returns
成功時は POTR_SUCCESS、失敗時は POTR_ERROR を返します。
受信スレッドを停止し、ソケットをクローズしてリソースを解放します。
マルチキャストの場合はグループから離脱します。
本関数呼び出し後、handle は無効となります。
Note
本関数呼び出し時、POTR_EVENT_DISCONNECTED コールバックは発火しません。
アプリケーション自身が明示的にサービスを閉じる操作は、接続状態変化イベントとして通知しない設計です。
送信者 (POTR_ROLE_SENDER) が本関数を呼び出した場合は、FIN パケットが送信されます。 FIN を受信した受信者側では POTR_EVENT_DISCONNECTED が発火します。
Warning
handle が NULL の場合は失敗を返します。
Definition at line 73 of file potrCloseService.c.
References comm_recv_thread_stop(), PotrContext_::compress_buf, PotrContext_::crypto_buf, PotrContext_::frag_buf, PotrContext_::health_running, PotrServiceDef::multicast_group, PotrContext_::n_path, parse_ipv4_addr(), POTR_API, POTR_ERROR, potr_health_thread_stop(), POTR_INVALID_SOCKET, POTR_LOG, POTR_LOG_DEBUG, POTR_LOG_ERROR, POTR_LOG_INFO, potr_send_queue_destroy(), potr_send_queue_wait_drained(), potr_send_thread_stop(), POTR_SUCCESS, POTR_TYPE_MULTICAST, POTRAPI, PotrContext_::recv_buf, PotrContext_::recv_window, PotrContext_::running, send_fin(), PotrContext_::send_queue, PotrContext_::send_thread_running, PotrContext_::send_window, PotrContext_::send_wire_buf, PotrContext_::service, PotrServiceDef::service_id, PotrContext_::sock, PotrContext_::src_addr_resolved, PotrServiceDef::type, and window_destroy().
Referenced by main().
potrLogConfig()
POTR_API int POTRAPI potrLogConfig (PotrLogLevel level, const char * log_file, int console) extern
ロガーを設定します。
Parameters
[in] level 出力する最低ログレベル。POTR_LOG_OFF でログ無効 (デフォルト)。
[in] log_file ログファイルのパス。NULL または空文字列を指定するとファイル出力なし。
[in] console 0 以外を指定すると標準エラー出力 (stderr) にも出力します。
Returns
成功時は POTR_SUCCESS、log_file が開けない場合は POTR_ERROR を返します。
本関数は potrOpenService() の前に呼び出してください。
複数回呼び出した場合は最後の設定が有効になります。
スレッドセーフです。
出力先
OS 出力先
Linux syslog (常時)、ログファイル (log_file 指定時)、stderr (console 指定時)
Windows ログファイル (log_file 指定時)、stderr (console 指定時)
ログフォーマット (ファイル / stderr)
[YYYY-MM-DD HH:MM:SS.mmm] [LEVEL] [file.c:line] message
ログレベル一覧
レベル 値 syslog priority 出力内容
POTR_LOG_TRACE 0 LOG_DEBUG パケット送受信・スレッド動作
POTR_LOG_DEBUG 1 LOG_DEBUG ソケット操作・設定値
POTR_LOG_INFO 2 LOG_INFO サービス開始・終了・接続状態変化
POTR_LOG_WARN 3 LOG_WARNING NACK・REJECT・回復可能な異常
POTR_LOG_ERROR 4 LOG_ERR 操作失敗
POTR_LOG_FATAL 5 LOG_CRIT 致命的エラー
POTR_LOG_OFF 6 - ログ無効 (デフォルト)
使用例
// INFO 以上をファイルと stderr に出力
potrLogConfig(POTR_LOG_INFO, "/var/log/porter.log", 1);
// DEBUG 以上をファイルのみに出力 (Linux では syslog にも出力)
potrLogConfig(POTR_LOG_DEBUG, "/tmp/porter.log", 0);
// ログを無効化
potrLogConfig(POTR_LOG_OFF, NULL, 0);
Warning
log_file に指定したパスが書き込み不可の場合は POTR_ERROR を返します。
本関数はロガー状態を再設定するため、呼び出し中にログを出力するスレッドが 存在する場合でも安全に動作します (内部でミューテックスを使用)。
Definition at line 194 of file potrLog.c.
References g_log_console, g_log_file_path, g_log_fp, g_log_level, g_syslog_open, log_lock(), log_unlock(), POTR_API, POTR_ERROR, POTR_LOG_FILE_PATH_MAX, POTR_LOG_OFF, POTR_SUCCESS, and POTRAPI.
Referenced by main().