Document of c-modernization-kit (porter): porter/libsrc/porter/thread/potrHealthThread.c File Reference
potrHealthThread.c File Reference
ヘルスチェックスレッドモジュール。
#include <string.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <time.h>
#include <porter_const.h>
#include <porter.h>
#include "../protocol/packet.h"
#include "../protocol/window.h"
#include "../potrContext.h"
#include "potrHealthThread.h"
#include "../infra/potrLog.h"
Functions
static void health_sleep (struct PotrContext_ *ctx, uint32_t interval_ms)
static uint64_t health_get_ms (void)
static void * health_thread_func (void *arg)
int potr_health_thread_start (struct PotrContext_ *ctx)
ヘルスチェックスレッドを起動します。
int potr_health_thread_stop (struct PotrContext_ *ctx)
ヘルスチェックスレッドを停止します。
Detailed Description
ヘルスチェックスレッドモジュール。
Author
c-modernization-kit sample team
Date
2026/03/08
Version
1.0.0
送信者側で動作する定周期 PING 送信スレッドです。
health_interval_ms 周期で PING パケットを送信します。
受信者側から送信者へのヘルスチェックは行いません (一方向ヘルスチェック)。
Copyright
Copyright (C) CompanyName, Ltd. 2026. All rights reserved.
Definition in file potrHealthThread.c.
Function Documentation
health_sleep()
void health_sleep (struct PotrContext_ * ctx, uint32_t interval_ms) static
Definition at line 41 of file potrHealthThread.c.
References PotrContext_::health_mutex, PotrContext_::health_running, and PotrContext_::health_wakeup.
Referenced by health_thread_func().
health_get_ms()
uint64_t health_get_ms (void) static
Definition at line 70 of file potrHealthThread.c.
Referenced by health_thread_func().
health_thread_func()
void * health_thread_func (void * arg) static
Definition at line 85 of file potrHealthThread.c.
References PotrPacketSessionHdr::_pad, PotrContext_::dest_addr, PotrContext_::global, health_get_ms(), PotrGlobalConfig::health_interval_ms, PotrContext_::health_running, health_sleep(), PotrContext_::last_send_ms, PotrContext_::n_path, PotrWindow::next_seq, packet_build_ping(), packet_wire_size(), POTR_LOG, POTR_LOG_TRACE, POTR_SUCCESS, PotrContext_::send_window, PotrContext_::send_window_mutex, PotrContext_::service, PotrPacketSessionHdr::service_id, PotrServiceDef::service_id, PotrContext_::session_id, PotrPacketSessionHdr::session_id, PotrContext_::session_tv_nsec, PotrPacketSessionHdr::session_tv_nsec, PotrContext_::session_tv_sec, PotrPacketSessionHdr::session_tv_sec, and PotrContext_::sock.
Referenced by potr_health_thread_start().
potr_health_thread_start()
int potr_health_thread_start (struct PotrContext_ * ctx)
ヘルスチェックスレッドを起動します。
Parameters
[in,out] ctx セッションコンテキストへのポインタ。
Returns
成功時は POTR_SUCCESS、失敗時は POTR_ERROR を返します。
ctx->global.health_interval_ms が 0 の場合は起動しません (POTR_SUCCESS を返します)。
Definition at line 227 of file potrHealthThread.c.
References PotrContext_::global, PotrGlobalConfig::health_interval_ms, PotrContext_::health_mutex, PotrContext_::health_running, PotrContext_::health_thread, health_thread_func(), PotrContext_::health_wakeup, POTR_ERROR, POTR_LOG, POTR_LOG_DEBUG, POTR_LOG_ERROR, POTR_SUCCESS, PotrContext_::service, and PotrServiceDef::service_id.
Referenced by potrOpenService().
potr_health_thread_stop()
int potr_health_thread_stop (struct PotrContext_ * ctx)
ヘルスチェックスレッドを停止します。
Parameters
[in,out] ctx セッションコンテキストへのポインタ。
Returns
成功時は POTR_SUCCESS、失敗時は POTR_ERROR を返します。
Definition at line 288 of file potrHealthThread.c.
References PotrContext_::health_mutex, PotrContext_::health_running, PotrContext_::health_thread, PotrContext_::health_wakeup, POTR_ERROR, and POTR_SUCCESS.
Referenced by potrCloseService(), and potrOpenService().