Document of c-modernization-kit (porter): porter/libsrc/porter/infra/potrLog.c File Reference
potrLog.c File Reference
porter ロガー実装。
#include <stdio.h>
#include <stdarg.h>
#include <string.h>
#include <syslog.h>
#include <pthread.h>
#include <time.h>
#include <porter_const.h>
#include <porter.h>
#include "potrLog.h"
Macros
#define POTR_LOG_FILE_PATH_MAX 512
出力ファイルパスの最大長 (終端 NUL を含む)。
Functions
static void log_lock (void)
static void log_unlock (void)
static const char * log_basename (const char *path)
パスの末尾ファイル名部分を返す。
static void log_timestamp (char *buf, size_t buflen)
現在時刻を "[YYYY-MM-DD HH:MM:SS.mmm]" 形式で buf に書き込む。
static int level_to_syslog_priority (PotrLogLevel level)
PotrLogLevel を syslog の priority に変換する (Linux のみ)。
POTR_API int POTRAPI potrLogConfig (PotrLogLevel level, const char *log_file, int console)
ロガーを設定します。
void potr_log_write (PotrLogLevel level, const char *file, int line, const char *fmt,...)
ログメッセージを書き込みます (内部関数)。
Variables
static const char *const s_level_str []
ログレベル表示文字列テーブル (POTR_LOG_TRACE〜POTR_LOG_FATAL の 6 エントリ)。
static pthread_mutex_t g_log_mutex = PTHREAD_MUTEX_INITIALIZER
出力先ミューテックスおよびロガー設定。スレッド間で共有する。
static int g_syslog_open = 0
openlog() 済みフラグ (1: 済み)。
static volatile int g_log_level = (int)POTR_LOG_OFF
出力ログレベル (POTR_LOG_OFF = 無効)。
static int g_log_console = 0
stderr 出力フラグ (非 0: 有効)。
static char g_log_file_path [POTR_LOG_FILE_PATH_MAX]
ログファイルパス (空文字列 = 無効)。
static FILE * g_log_fp = NULL
ログファイル FILE ポインタ (NULL = 未オープン)。
Detailed Description
porter ロガー実装。
Author
c-modernization-kit sample team
Date
2026/03/09
Version
1.0.0
クロスプラットフォーム対応のロガーモジュールです。
追加の OSS ライブラリを必要とせず、OS 標準 API のみを使用します。
OS 出力先
Linux syslog (常時)、ログファイル (log_file 指定時)、stderr (console 指定時)
Windows ログファイル (log_file 指定時)、stderr (console 指定時)
スレッドセーフ:
Linux: PTHREAD_MUTEX_INITIALIZER による静的初期化済みミューテックスを使用。
Windows: INIT_ONCE_STATIC_INIT + InitOnceExecuteOnce による遅延初期化。
Copyright
Copyright (C) CompanyName, Ltd. 2026. All rights reserved.
Definition in file potrLog.c.
Macro Definition Documentation
POTR_LOG_FILE_PATH_MAX
#define POTR_LOG_FILE_PATH_MAX 512
出力ファイルパスの最大長 (終端 NUL を含む)。
Definition at line 59 of file potrLog.c.
Referenced by potrLogConfig().
Function Documentation
log_lock()
void log_lock (void) static
Definition at line 92 of file potrLog.c.
References g_log_mutex.
Referenced by potr_log_write(), and potrLogConfig().
log_unlock()
void log_unlock (void) static
Definition at line 97 of file potrLog.c.
References g_log_mutex.
Referenced by potr_log_write(), and potrLogConfig().
log_basename()
const char * log_basename (const char * path) static
パスの末尾ファイル名部分を返す。
'/' または '\' の最後の出現以降の文字列を返します。
区切り文字が存在しない場合は path をそのまま返します。
Definition at line 125 of file potrLog.c.
Referenced by potr_log_write().
log_timestamp()
void log_timestamp (char * buf, size_t buflen) static
現在時刻を "[YYYY-MM-DD HH:MM:SS.mmm]" 形式で buf に書き込む。
Parameters
[out] buf 出力バッファ (最低 96 バイト)。
[in] buflen バッファサイズ。
Definition at line 146 of file potrLog.c.
Referenced by potr_log_write().
level_to_syslog_priority()
int level_to_syslog_priority (PotrLogLevel level) static
PotrLogLevel を syslog の priority に変換する (Linux のみ)。
Definition at line 175 of file potrLog.c.
References POTR_LOG_DEBUG, POTR_LOG_ERROR, POTR_LOG_FATAL, POTR_LOG_INFO, POTR_LOG_OFF, POTR_LOG_TRACE, and POTR_LOG_WARN.
Referenced by potr_log_write().
potrLogConfig()
POTR_API int POTRAPI potrLogConfig (PotrLogLevel level, const char * log_file, int console)
ロガーを設定します。
Parameters
[in] level 出力する最低ログレベル。POTR_LOG_OFF でログ無効 (デフォルト)。
[in] log_file ログファイルのパス。NULL または空文字列を指定するとファイル出力なし。
[in] console 0 以外を指定すると標準エラー出力 (stderr) にも出力します。
Returns
成功時は POTR_SUCCESS、log_file が開けない場合は POTR_ERROR を返します。
本関数は potrOpenService() の前に呼び出してください。
複数回呼び出した場合は最後の設定が有効になります。
スレッドセーフです。
出力先
OS 出力先
Linux syslog (常時)、ログファイル (log_file 指定時)、stderr (console 指定時)
Windows ログファイル (log_file 指定時)、stderr (console 指定時)
ログフォーマット (ファイル / stderr)
[YYYY-MM-DD HH:MM:SS.mmm] [LEVEL] [file.c:line] message
ログレベル一覧
レベル 値 syslog priority 出力内容
POTR_LOG_TRACE 0 LOG_DEBUG パケット送受信・スレッド動作
POTR_LOG_DEBUG 1 LOG_DEBUG ソケット操作・設定値
POTR_LOG_INFO 2 LOG_INFO サービス開始・終了・接続状態変化
POTR_LOG_WARN 3 LOG_WARNING NACK・REJECT・回復可能な異常
POTR_LOG_ERROR 4 LOG_ERR 操作失敗
POTR_LOG_FATAL 5 LOG_CRIT 致命的エラー
POTR_LOG_OFF 6 - ログ無効 (デフォルト)
使用例
// INFO 以上をファイルと stderr に出力
potrLogConfig(POTR_LOG_INFO, "/var/log/porter.log", 1);
// DEBUG 以上をファイルのみに出力 (Linux では syslog にも出力)
potrLogConfig(POTR_LOG_DEBUG, "/tmp/porter.log", 0);
// ログを無効化
potrLogConfig(POTR_LOG_OFF, NULL, 0);
Warning
log_file に指定したパスが書き込み不可の場合は POTR_ERROR を返します。
本関数はロガー状態を再設定するため、呼び出し中にログを出力するスレッドが 存在する場合でも安全に動作します (内部でミューテックスを使用)。
Definition at line 194 of file potrLog.c.
References g_log_console, g_log_file_path, g_log_fp, g_log_level, g_syslog_open, log_lock(), log_unlock(), POTR_API, POTR_ERROR, POTR_LOG_FILE_PATH_MAX, POTR_LOG_OFF, POTR_SUCCESS, and POTRAPI.
Referenced by main().
potr_log_write()
void potr_log_write (PotrLogLevel level, const char * file, int line, const char * fmt, ...)
ログメッセージを書き込みます (内部関数)。
Parameters
[in] level ログレベル。
[in] file ソースファイル名 (FILE)。
[in] line 行番号 (LINE)。
[in] fmt printf 形式のフォーマット文字列。
[in] ... フォーマット引数。
g_log_level より低いレベルのメッセージは無視されます (高速パス)。
本関数を直接呼び出さず、POTR_LOG マクロを使用してください。
Definition at line 270 of file potrLog.c.
References g_log_console, g_log_fp, g_log_level, g_syslog_open, level_to_syslog_priority(), log_basename(), log_lock(), log_timestamp(), log_unlock(), POTR_LOG_FATAL, POTR_LOG_OFF, and s_level_str.
Variable Documentation
s_level_str
const char* const s_level_str[] static
Initial value:
= {
    "TRACE",
    "DEBUG",
    "INFO ",
    "WARN ",
    "ERROR",
    "FATAL",
}
ログレベル表示文字列テーブル (POTR_LOG_TRACE〜POTR_LOG_FATAL の 6 エントリ)。
Definition at line 47 of file potrLog.c.
Referenced by potr_log_write().
g_log_mutex
pthread_mutex_t g_log_mutex = PTHREAD_MUTEX_INITIALIZER static
出力先ミューテックスおよびロガー設定。スレッド間で共有する。
Definition at line 89 of file potrLog.c.
Referenced by log_lock(), and log_unlock().
g_syslog_open
int g_syslog_open = 0 static
openlog() 済みフラグ (1: 済み)。
Definition at line 90 of file potrLog.c.
Referenced by potr_log_write(), and potrLogConfig().
g_log_level
volatile int g_log_level = (int)POTR_LOG_OFF static
出力ログレベル (POTR_LOG_OFF = 無効)。
Definition at line 105 of file potrLog.c.
Referenced by potr_log_write(), and potrLogConfig().
g_log_console
int g_log_console = 0 static
stderr 出力フラグ (非 0: 有効)。
Definition at line 108 of file potrLog.c.
Referenced by potr_log_write(), and potrLogConfig().
g_log_file_path
char g_log_file_path[POTR_LOG_FILE_PATH_MAX] static
ログファイルパス (空文字列 = 無効)。
Definition at line 111 of file potrLog.c.
Referenced by potrLogConfig().
g_log_fp
FILE* g_log_fp = NULL static
ログファイル FILE ポインタ (NULL = 未オープン)。
Definition at line 114 of file potrLog.c.
Referenced by potr_log_write(), and potrLogConfig().