Document of c-modernization-kit (porter): porter/libsrc/porter/api/potrCloseService.c File Reference
potrCloseService.c File Reference
#include <stdlib.h>
#include <string.h>
#include <arpa/inet.h>
#include <netinet/in.h>
#include <sys/socket.h>
#include <unistd.h>
#include <porter_const.h>
#include <porter.h>
#include "../potrContext.h"
#include "../thread/potrRecvThread.h"
#include "../thread/potrHealthThread.h"
#include "../infra/potrSendQueue.h"
#include "../thread/potrSendThread.h"
#include "../protocol/packet.h"
#include "../protocol/window.h"
#include "../util/potrIpAddr.h"
#include "../infra/potrLog.h"
Functions
static void send_fin (struct PotrContext_ *ctx)
POTR_API int POTRAPI potrCloseService (PotrHandle handle)
サービスを閉じます。
Function Documentation
send_fin()
void send_fin (struct PotrContext_ * ctx) static
Definition at line 41 of file potrCloseService.c.
References PotrContext_::dest_addr, PotrContext_::n_path, packet_build_fin(), packet_wire_size(), POTR_INVALID_SOCKET, POTR_SUCCESS, PotrContext_::service, PotrPacketSessionHdr::service_id, PotrServiceDef::service_id, PotrContext_::session_id, PotrPacketSessionHdr::session_id, PotrContext_::session_tv_nsec, PotrPacketSessionHdr::session_tv_nsec, PotrContext_::session_tv_sec, PotrPacketSessionHdr::session_tv_sec, and PotrContext_::sock.
Referenced by potrCloseService().
potrCloseService()
POTR_API int POTRAPI potrCloseService (PotrHandle handle)
サービスを閉じます。
Parameters
[in] handle potrOpenService() で取得したセッションハンドル。
Returns
成功時は POTR_SUCCESS、失敗時は POTR_ERROR を返します。
受信スレッドを停止し、ソケットをクローズしてリソースを解放します。
マルチキャストの場合はグループから離脱します。
本関数呼び出し後、handle は無効となります。
Note
本関数呼び出し時、POTR_EVENT_DISCONNECTED コールバックは発火しません。
アプリケーション自身が明示的にサービスを閉じる操作は、接続状態変化イベントとして通知しない設計です。
送信者 (POTR_ROLE_SENDER) が本関数を呼び出した場合は、FIN パケットが送信されます。 FIN を受信した受信者側では POTR_EVENT_DISCONNECTED が発火します。
Warning
handle が NULL の場合は失敗を返します。
Definition at line 73 of file potrCloseService.c.
References comm_recv_thread_stop(), PotrContext_::compress_buf, PotrContext_::crypto_buf, PotrContext_::frag_buf, PotrContext_::health_running, PotrServiceDef::multicast_group, PotrContext_::n_path, parse_ipv4_addr(), POTR_API, POTR_ERROR, potr_health_thread_stop(), POTR_INVALID_SOCKET, POTR_LOG, POTR_LOG_DEBUG, POTR_LOG_ERROR, POTR_LOG_INFO, potr_send_queue_destroy(), potr_send_queue_wait_drained(), potr_send_thread_stop(), POTR_SUCCESS, POTR_TYPE_MULTICAST, POTRAPI, PotrContext_::recv_buf, PotrContext_::recv_window, PotrContext_::running, send_fin(), PotrContext_::send_queue, PotrContext_::send_thread_running, PotrContext_::send_window, PotrContext_::send_wire_buf, PotrContext_::service, PotrServiceDef::service_id, PotrContext_::sock, PotrContext_::src_addr_resolved, PotrServiceDef::type, and window_destroy().
Referenced by main().