Document of c-modernization-kit (porter): porter/libsrc/porter/potrClose.c File Reference
potrClose.c File Reference
potrClose 関数の実装。
#include <stdlib.h>
#include <string.h>
#include <arpa/inet.h>
#include <netinet/in.h>
#include <sys/socket.h>
#include <unistd.h>
#include <porter_const.h>
#include <porter.h>
#include "potrContext.h"
#include "potrRecvThread.h"
#include "util/potrIpAddr.h"
Functions
POTR_API int POTRAPI potrClose (PotrHandle handle)
サービスを閉じます。
Detailed Description
potrClose 関数の実装。
Author
c-modernization-kit sample team
Date
2026/03/04
Version
1.0.0
Copyright
Copyright (C) CompanyName, Ltd. 2026. All rights reserved.
Definition in file potrClose.c.
Function Documentation
potrClose()
POTR_API int POTRAPI potrClose (PotrHandle handle)
サービスを閉じます。
Parameters
[in] handle potrOpenService() で取得したセッションハンドル。
Returns
成功時は POTR_SUCCESS、失敗時は POTR_ERROR を返します。
受信スレッドを停止し、ソケットをクローズしてリソースを解放します。
マルチキャストの場合はグループから離脱します。
本関数呼び出し後、handle は無効となります。
Warning
handle が NULL の場合は失敗を返します。
Definition at line 35 of file potrClose.c.
References comm_recv_thread_stop(), PotrServiceDef::multicast_group, parse_ipv4_addr(), POTR_API, POTR_ERROR, POTR_INVALID_SOCKET, POTR_SUCCESS, POTR_TYPE_MULTICAST, POTRAPI, PotrContext_::running, PotrContext_::service, PotrContext_::sock, and PotrServiceDef::type.
Referenced by main().