Document of c-modernization-kit (porter): porter/libsrc/porter/api/potrOpenService.c File Reference
potrOpenService.c File Reference
potrOpenService 関数の実装。
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <unistd.h>
#include <time.h>
#include <porter_const.h>
#include <porter.h>
#include "../protocol/config.h"
#include "../protocol/packet.h"
#include "../protocol/window.h"
#include "../potrContext.h"
#include "../thread/potrRecvThread.h"
#include "../thread/potrHealthThread.h"
#include "../infra/compress/compress.h"
#include "../infra/potrSendQueue.h"
#include "../thread/potrSendThread.h"
#include "../util/potrIpAddr.h"
#include "../infra/potrLog.h"
Functions
static PotrSocket open_socket_unicast (struct in_addr bind_addr, uint16_t port)
static void generate_session (struct PotrContext_ *ctx)
static PotrSocket open_socket_multicast (const PotrServiceDef *def, struct in_addr src_if, int is_receiver)
static PotrSocket open_socket_broadcast (uint16_t src_port, uint16_t dst_port, struct in_addr src_if, int is_receiver)
static void cleanup_sockets (struct PotrContext_ *ctx)
static void ctx_cleanup (struct PotrContext_ *ctx)
POTR_API int POTRAPI potrOpenService (const char *config_path, int service_id, PotrRole role, PotrRecvCallback callback, PotrHandle *handle)
設定ファイルから指定サービスを開きます。
Detailed Description
potrOpenService 関数の実装。
Author
c-modernization-kit sample team
Date
2026/03/04
Version
1.0.0
Copyright
Copyright (C) CompanyName, Ltd. 2026. All rights reserved.
Definition in file potrOpenService.c.
Function Documentation
open_socket_unicast()
PotrSocket open_socket_unicast (struct in_addr bind_addr, uint16_t port) static
Definition at line 45 of file potrOpenService.c.
References POTR_INVALID_SOCKET.
Referenced by potrOpenService().
generate_session()
void generate_session (struct PotrContext_ * ctx) static
Definition at line 83 of file potrOpenService.c.
References PotrContext_::session_id, PotrContext_::session_tv_nsec, and PotrContext_::session_tv_sec.
Referenced by potrOpenService().
open_socket_multicast()
PotrSocket open_socket_multicast (const PotrServiceDef * def, struct in_addr src_if, int is_receiver) static
Definition at line 113 of file potrOpenService.c.
References PotrServiceDef::dst_port, PotrServiceDef::multicast_group, parse_ipv4_addr(), POTR_INVALID_SOCKET, POTR_SUCCESS, and PotrServiceDef::src_port.
Referenced by potrOpenService().
open_socket_broadcast()
PotrSocket open_socket_broadcast (uint16_t src_port, uint16_t dst_port, struct in_addr src_if, int is_receiver) static
Definition at line 209 of file potrOpenService.c.
References POTR_INVALID_SOCKET.
Referenced by potrOpenService().
cleanup_sockets()
void cleanup_sockets (struct PotrContext_ * ctx) static
Definition at line 272 of file potrOpenService.c.
References POTR_INVALID_SOCKET, POTR_MAX_PATH, and PotrContext_::sock.
Referenced by ctx_cleanup().
ctx_cleanup()
void ctx_cleanup (struct PotrContext_ * ctx) static
Definition at line 291 of file potrOpenService.c.
References cleanup_sockets(), PotrContext_::compress_buf, PotrContext_::crypto_buf, PotrContext_::frag_buf, PotrContext_::recv_buf, PotrContext_::recv_window, PotrContext_::send_window, PotrContext_::send_wire_buf, and window_destroy().
Referenced by potrOpenService().
potrOpenService()
POTR_API int POTRAPI potrOpenService (const char * config_path, int service_id, PotrRole role, PotrRecvCallback callback, PotrHandle * handle)
設定ファイルから指定サービスを開きます。
Parameters
[in] config_path 設定ファイルのパス。
[in] service_id 開くサービスの ID。
[in] role 役割種別。POTR_ROLE_SENDER または POTR_ROLE_RECEIVER。
[in] callback イベント発生時に呼び出されるコールバック関数 (PotrRecvCallback)。 POTR_ROLE_RECEIVER の場合は必須。データ受信・接続検知・切断検知を受け取る。 POTR_ROLE_SENDER の場合は NULL を指定すること。
[out] handle 成功時にセッションハンドルを格納するポインタ。
Returns
成功時は POTR_SUCCESS、失敗時は POTR_ERROR を返します。
設定ファイルを解析してサービス定義を取得し、UDP ソケットを初期化します。
role と callback の組み合わせが不正な場合は POTR_ERROR を返します。
role と設定ファイルの IP アドレスが不整合 (bind 失敗など) の場合も POTR_ERROR を返します。
通信種別・役割に応じて以下のソケット設定を行います。
通信種別 役割 bind アドレス bind ポート
POTR_TYPE_UNICAST 送信者 src_addr src_port
POTR_TYPE_UNICAST 受信者 dst_addr dst_port
POTR_TYPE_MULTICAST 送信者 INADDR_ANY src_port
POTR_TYPE_MULTICAST 受信者 INADDR_ANY dst_port
POTR_TYPE_BROADCAST 送信者 src_addr src_port
POTR_TYPE_BROADCAST 受信者 INADDR_ANY dst_port
POTR_ROLE_RECEIVER の場合、内部で受信スレッドを起動します。
使用例 (受信者)
void on_recv(int service_id, PotrEvent event,
             const void *data, size_t len) {
    if (event == POTR_EVENT_CONNECTED)
        printf("service %d: connected\n", service_id);
    else if (event == POTR_EVENT_DISCONNECTED)
        printf("service %d: disconnected\n", service_id);
    else
        printf("service %d: received %zu bytes\n", service_id, len);
}
PotrHandle handle;
if (potrOpenService("porter-services.conf", 1001,
                    POTR_ROLE_RECEIVER, on_recv, &handle) == POTR_SUCCESS) {
    // 受信待機中 (受信スレッドが動作)
    potrCloseService(handle);
}
使用例 (送信者)
PotrHandle handle;
if (potrOpenService("porter-services.conf", 1001,
                    POTR_ROLE_SENDER, NULL, &handle) == POTR_SUCCESS) {
    potrSend(handle, "hello", 5, 0);
    potrCloseService(handle);
}
Warning
handle が NULL の場合は失敗を返します。
config_path が NULL または存在しない場合は失敗を返します。
指定した service_id が設定ファイルに存在しない場合は失敗を返します。
POTR_ROLE_RECEIVER かつ callback が NULL の場合は失敗を返します。
POTR_ROLE_SENDER かつ callback が NULL でない場合は失敗を返します。
Definition at line 305 of file potrOpenService.c.
References PotrServiceDef::broadcast_addr, PotrContext_::callback, comm_recv_thread_start(), PotrContext_::compress_buf, PotrContext_::compress_buf_size, config_load_global(), config_load_service(), PotrContext_::crypto_buf, PotrContext_::crypto_buf_size, ctx_cleanup(), PotrContext_::dest_addr, PotrServiceDef::dst_addr, PotrContext_::dst_addr_resolved, PotrServiceDef::dst_port, PotrServiceDef::encrypt_enabled, PotrContext_::frag_buf, generate_session(), PotrContext_::global, PotrGlobalConfig::health_interval_ms, PotrGlobalConfig::health_timeout_ms, PotrGlobalConfig::max_message_size, PotrGlobalConfig::max_payload, PotrServiceDef::multicast_group, PotrContext_::n_path, open_socket_broadcast(), open_socket_multicast(), open_socket_unicast(), PACKET_HEADER_SIZE, parse_ipv4_addr(), POTR_API, POTR_COMPRESS_HEADER_SIZE, POTR_CRYPTO_TAG_SIZE, POTR_ERROR, potr_health_thread_start(), potr_health_thread_stop(), POTR_INVALID_SOCKET, POTR_LOG, POTR_LOG_DEBUG, POTR_LOG_ERROR, POTR_LOG_INFO, POTR_MAX_PATH, POTR_MAX_PAYLOAD, POTR_MAX_WINDOW_SIZE, POTR_ROLE_RECEIVER, POTR_ROLE_SENDER, potr_send_queue_destroy(), potr_send_queue_init(), potr_send_thread_start(), potr_send_thread_stop(), POTR_SUCCESS, POTR_TYPE_BROADCAST, POTR_TYPE_MULTICAST, POTR_TYPE_UNICAST, POTRAPI, PotrContext_::recv_buf, PotrContext_::recv_window, resolve_ipv4_addr(), PotrContext_::role, PotrContext_::send_queue, PotrGlobalConfig::send_queue_depth, PotrContext_::send_window, PotrContext_::send_wire_buf, PotrContext_::service, PotrContext_::sock, PotrServiceDef::src_addr, PotrContext_::src_addr_resolved, PotrServiceDef::src_port, PotrServiceDef::type, window_init(), and PotrGlobalConfig::window_size.
Referenced by main().