Document of c-modernization-kit (porter): porter/libsrc/porter/util/potrIpAddr.h File Reference
potrIpAddr.h File Reference
IPv4 アドレス変換ユーティリティ (内部用)。
#include <arpa/inet.h>
#include <netinet/in.h>
Functions
int parse_ipv4_addr (const char *ip_str, struct in_addr *out_addr)
int resolve_ipv4_addr (const char *host, struct in_addr *out_addr)
ホスト名または IPv4 アドレス文字列を struct in_addr に解決する。
Detailed Description
IPv4 アドレス変換ユーティリティ (内部用)。
Author
c-modernization-kit sample team
Date
2026/03/05
Version
1.0.0
Copyright
Copyright (C) CompanyName, Ltd. 2026. All rights reserved.
Definition in file potrIpAddr.h.
Function Documentation
parse_ipv4_addr()
int parse_ipv4_addr (const char * ip_str, struct in_addr * out_addr)
Definition at line 28 of file potrIpAddr.c.
References POTR_ERROR, and POTR_SUCCESS.
Referenced by open_socket_multicast(), potrCloseService(), and potrOpenService().
resolve_ipv4_addr()
int resolve_ipv4_addr (const char * host, struct in_addr * out_addr)
ホスト名または IPv4 アドレス文字列を struct in_addr に解決する。
getaddrinfo() を使用して AF_INET で名前解決する。 複数のアドレスが返された場合は先頭のアドレスを採用する。
Definition at line 46 of file potrIpAddr.c.
References POTR_ERROR, and POTR_SUCCESS.
Referenced by potrOpenService().