Document of c-modernization-kit (porter): porter/libsrc/porter/thread/potrRecvThread.c File Reference
potrRecvThread.c File Reference
受信スレッドモジュール。
#include <string.h>
#include <sys/socket.h>
#include <sys/select.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <unistd.h>
#include <time.h>
#include <errno.h>
#include <porter_const.h>
#include "../protocol/packet.h"
#include "../protocol/seqnum.h"
#include "../protocol/window.h"
#include "../potrContext.h"
#include "potrRecvThread.h"
#include "../infra/compress/compress.h"
#include "../infra/crypto/crypto.h"
#include "../infra/potrLog.h"
Macros
#define POTR_NACK_DEDUP_MS 200U
NACK 重複抑制の時間窓 (ミリ秒)。この時間内の同一 ack_num の NACK は破棄する。
Functions
static void recv_deliver (struct PotrContext_ *ctx, const uint8_t *payload, size_t payload_len, int compressed)
static int check_src_addr (const struct PotrContext_ *ctx, const struct sockaddr_in *sender)
static int check_and_update_session (struct PotrContext_ *ctx, const PotrPacket *pkt)
static uint64_t get_ms_mono (void)
static void get_monotonic (int64_t *tv_sec, int32_t *tv_nsec)
static void update_path_recv (struct PotrContext_ *ctx, int path_idx, const struct sockaddr_in *sender)
static void notify_health_alive (struct PotrContext_ *ctx)
static void check_health_timeout (struct PotrContext_ *ctx)
static void send_nack (struct PotrContext_ *ctx, uint32_t nack_seq)
static void send_reject (struct PotrContext_ *ctx, uint32_t seq_num)
static void deliver_payload_elem (struct PotrContext_ *ctx, const PotrPacket *elem)
static void drain_recv_window (struct PotrContext_ *ctx)
static void process_outer_pkt (struct PotrContext_ *ctx, const PotrPacket *pkt)
static void * recv_thread_func (void *arg)
int comm_recv_thread_start (struct PotrContext_ *ctx)
受信スレッドを起動します。
int comm_recv_thread_stop (struct PotrContext_ *ctx)
受信スレッドを停止します。
Detailed Description
受信スレッドモジュール。
Author
c-modernization-kit sample team
Date
2026/03/04
Version
1.0.0
Copyright
Copyright (C) CompanyName, Ltd. 2026. All rights reserved.
Definition in file potrRecvThread.c.
Macro Definition Documentation
POTR_NACK_DEDUP_MS
#define POTR_NACK_DEDUP_MS 200U
NACK 重複抑制の時間窓 (ミリ秒)。この時間内の同一 ack_num の NACK は破棄する。
Definition at line 162 of file potrRecvThread.c.
Referenced by recv_thread_func().
Function Documentation
recv_deliver()
void recv_deliver (struct PotrContext_ * ctx, const uint8_t * payload, size_t payload_len, int compressed) static
Definition at line 362 of file potrRecvThread.c.
References PotrContext_::callback, PotrContext_::compress_buf, PotrContext_::compress_buf_size, potr_decompress(), POTR_EVENT_DATA, POTR_LOG, POTR_LOG_ERROR, POTR_LOG_TRACE, PotrContext_::service, and PotrServiceDef::service_id.
Referenced by deliver_payload_elem().
check_src_addr()
int check_src_addr (const struct PotrContext_ * ctx, const struct sockaddr_in * sender) static
Definition at line 46 of file potrRecvThread.c.
References PotrContext_::n_path, PotrContext_::service, PotrServiceDef::src_addr, and PotrContext_::src_addr_resolved.
Referenced by recv_thread_func().
check_and_update_session()
int check_and_update_session (struct PotrContext_ * ctx, const PotrPacket * pkt) static
Definition at line 66 of file potrRecvThread.c.
References PotrContext_::global, PotrGlobalConfig::max_payload, PotrContext_::peer_session_id, PotrContext_::peer_session_known, PotrContext_::peer_session_tv_nsec, PotrContext_::peer_session_tv_sec, POTR_LOG, POTR_LOG_TRACE, PotrContext_::recv_window, PotrPacket::seq_num, PotrContext_::service, PotrServiceDef::service_id, PotrPacket::session_id, PotrPacket::session_tv_nsec, PotrPacket::session_tv_sec, window_init(), and PotrGlobalConfig::window_size.
Referenced by recv_thread_func().
get_ms_mono()
uint64_t get_ms_mono (void) static
Definition at line 165 of file potrRecvThread.c.
Referenced by recv_thread_func().
get_monotonic()
void get_monotonic (int64_t * tv_sec, int32_t * tv_nsec) static
Definition at line 177 of file potrRecvThread.c.
Referenced by check_health_timeout(), and update_path_recv().
update_path_recv()
void update_path_recv (struct PotrContext_ * ctx, int path_idx, const struct sockaddr_in * sender) static
Definition at line 192 of file potrRecvThread.c.
References get_monotonic(), PotrContext_::last_recv_tv_nsec, PotrContext_::last_recv_tv_sec, PotrContext_::path_last_recv_nsec, PotrContext_::path_last_recv_sec, and PotrContext_::peer_port.
Referenced by recv_thread_func().
notify_health_alive()
void notify_health_alive (struct PotrContext_ * ctx) static
Definition at line 204 of file potrRecvThread.c.
References PotrContext_::callback, PotrContext_::health_alive, POTR_EVENT_CONNECTED, POTR_LOG, POTR_LOG_INFO, PotrContext_::service, and PotrServiceDef::service_id.
Referenced by drain_recv_window(), and recv_thread_func().
check_health_timeout()
void check_health_timeout (struct PotrContext_ * ctx) static
Definition at line 221 of file potrRecvThread.c.
References PotrContext_::callback, get_monotonic(), PotrContext_::global, PotrContext_::health_alive, PotrGlobalConfig::health_timeout_ms, PotrContext_::last_recv_tv_nsec, PotrContext_::last_recv_tv_sec, PotrGlobalConfig::max_payload, PotrContext_::n_path, PotrContext_::path_last_recv_nsec, PotrContext_::path_last_recv_sec, PotrContext_::peer_port, PotrContext_::peer_session_known, POTR_EVENT_DISCONNECTED, POTR_LOG, POTR_LOG_WARN, PotrContext_::recv_window, PotrContext_::service, PotrServiceDef::service_id, window_init(), and PotrGlobalConfig::window_size.
Referenced by recv_thread_func().
send_nack()
void send_nack (struct PotrContext_ * ctx, uint32_t nack_seq) static
Definition at line 283 of file potrRecvThread.c.
References PotrContext_::n_path, packet_build_nack(), packet_wire_size(), PotrContext_::peer_port, POTR_SUCCESS, PotrContext_::service, PotrPacketSessionHdr::service_id, PotrServiceDef::service_id, PotrContext_::session_id, PotrPacketSessionHdr::session_id, PotrContext_::session_tv_nsec, PotrPacketSessionHdr::session_tv_nsec, PotrContext_::session_tv_sec, PotrPacketSessionHdr::session_tv_sec, PotrContext_::sock, PotrContext_::src_addr_resolved, and PotrServiceDef::src_port.
Referenced by process_outer_pkt(), and recv_thread_func().
send_reject()
void send_reject (struct PotrContext_ * ctx, uint32_t seq_num) static
Definition at line 331 of file potrRecvThread.c.
References PotrContext_::dest_addr, PotrContext_::n_path, packet_build_reject(), packet_wire_size(), POTR_SUCCESS, PotrContext_::service, PotrPacketSessionHdr::service_id, PotrServiceDef::service_id, PotrContext_::session_id, PotrPacketSessionHdr::session_id, PotrContext_::session_tv_nsec, PotrPacketSessionHdr::session_tv_nsec, PotrContext_::session_tv_sec, PotrPacketSessionHdr::session_tv_sec, and PotrContext_::sock.
Referenced by recv_thread_func().
deliver_payload_elem()
void deliver_payload_elem (struct PotrContext_ * ctx, const PotrPacket * elem) static
Definition at line 399 of file potrRecvThread.c.
References PotrContext_::callback, PotrPacket::flags, PotrContext_::frag_buf, PotrContext_::frag_buf_len, PotrContext_::frag_compressed, PotrContext_::global, PotrGlobalConfig::max_message_size, PotrPacket::payload, PotrPacket::payload_len, POTR_FLAG_COMPRESSED, POTR_FLAG_MORE_FRAG, and recv_deliver().
Referenced by drain_recv_window().
drain_recv_window()
void drain_recv_window (struct PotrContext_ * ctx) static
Definition at line 469 of file potrRecvThread.c.
References deliver_payload_elem(), PotrPacket::flags, notify_health_alive(), packet_unpack_next(), POTR_FLAG_PING, POTR_LOG, POTR_LOG_TRACE, POTR_SUCCESS, PotrContext_::recv_window, PotrPacket::seq_num, PotrContext_::service, PotrServiceDef::service_id, and window_recv_pop().
Referenced by process_outer_pkt(), and recv_thread_func().
process_outer_pkt()
void process_outer_pkt (struct PotrContext_ * ctx, const PotrPacket * pkt) static
Definition at line 512 of file potrRecvThread.c.
References PotrWindow::base_seq, drain_recv_window(), POTR_LOG, POTR_LOG_DEBUG, POTR_LOG_ERROR, POTR_LOG_WARN, POTR_SUCCESS, PotrContext_::recv_window, send_nack(), PotrPacket::seq_num, PotrContext_::service, PotrServiceDef::service_id, window_recv_needs_nack(), window_recv_push(), and PotrWindow::window_size.
Referenced by recv_thread_func().
recv_thread_func()
void * recv_thread_func (void * arg) static
Definition at line 570 of file potrRecvThread.c.
References PotrNackDedupEntry::ack_num, PotrPacket::ack_num, PotrWindow::base_seq, PotrContext_::callback, check_and_update_session(), check_health_timeout(), check_src_addr(), PotrContext_::crypto_buf, PotrContext_::crypto_buf_size, PotrContext_::dest_addr, drain_recv_window(), PotrServiceDef::encrypt_key, PotrPacket::flags, get_ms_mono(), PotrContext_::global, PotrContext_::health_alive, PotrGlobalConfig::health_timeout_ms, PotrContext_::last_recv_tv_sec, PotrGlobalConfig::max_payload, PotrContext_::n_path, PotrContext_::nack_dedup_buf, PotrContext_::nack_dedup_next, PotrWindow::next_seq, notify_health_alive(), PACKET_HEADER_SIZE, packet_parse(), packet_wire_size(), PotrPacket::payload, PotrPacket::payload_len, PotrContext_::peer_session_known, POTR_CRYPTO_NONCE_SIZE, potr_decrypt(), POTR_EVENT_DISCONNECTED, POTR_FLAG_DATA, POTR_FLAG_ENCRYPTED, POTR_FLAG_FIN, POTR_FLAG_NACK, POTR_FLAG_PING, POTR_FLAG_REJECT, POTR_INVALID_SOCKET, POTR_LOG, POTR_LOG_DEBUG, POTR_LOG_INFO, POTR_LOG_TRACE, POTR_LOG_WARN, POTR_NACK_DEDUP_MS, POTR_NACK_DEDUP_SLOTS, POTR_ROLE_RECEIVER, POTR_ROLE_SENDER, POTR_SUCCESS, process_outer_pkt(), PotrContext_::recv_buf, PotrContext_::recv_window, PotrContext_::role, PotrContext_::running, send_nack(), send_reject(), PotrContext_::send_window, PotrContext_::send_window_mutex, PotrPacket::seq_num, seqnum_in_window(), PotrContext_::service, PotrPacket::service_id, PotrServiceDef::service_id, PotrPacket::session_id, PotrContext_::sock, PotrNackDedupEntry::time_ms, update_path_recv(), PotrWindow::valid, window_init(), window_recv_skip(), window_send_get(), PotrGlobalConfig::window_size, and PotrWindow::window_size.
Referenced by comm_recv_thread_start().
comm_recv_thread_start()
int comm_recv_thread_start (struct PotrContext_ * ctx)
受信スレッドを起動します。
Parameters
[in,out] ctx セッションコンテキストへのポインタ。
Returns
成功時は POTR_SUCCESS、失敗時は POTR_ERROR を返します。
Definition at line 982 of file potrRecvThread.c.
References POTR_ERROR, POTR_LOG, POTR_LOG_DEBUG, POTR_LOG_ERROR, POTR_SUCCESS, PotrContext_::recv_thread, recv_thread_func(), PotrContext_::running, PotrContext_::service, and PotrServiceDef::service_id.
Referenced by potrOpenService().
comm_recv_thread_stop()
int comm_recv_thread_stop (struct PotrContext_ * ctx)
受信スレッドを停止します。
Parameters
[in,out] ctx セッションコンテキストへのポインタ。
Returns
成功時は POTR_SUCCESS、失敗時は POTR_ERROR を返します。
Definition at line 1026 of file potrRecvThread.c.
References PotrContext_::n_path, POTR_ERROR, POTR_INVALID_SOCKET, POTR_SUCCESS, PotrContext_::recv_thread, PotrContext_::running, and PotrContext_::sock.
Referenced by potrCloseService().