Document of c-modernization-kit (porter): porter/libsrc/porter/thread/potrSendThread.h File Reference
potrSendThread.h File Reference
非同期送信スレッドの内部ヘッダー。
#include "../potrContext.h"
Functions
int potr_send_thread_start (struct PotrContext_ *ctx)
void potr_send_thread_stop (struct PotrContext_ *ctx)
Detailed Description
非同期送信スレッドの内部ヘッダー。
Author
c-modernization-kit sample team
Date
2026/03/08
Version
1.0.0
送信者 (POTR_ROLE_SENDER) が非ブロッキング送信を使用する場合に起動する 送信スレッドの起動・停止 API。
送信スレッドは送信キュー (PotrSendQueue) からペイロードエレメントを取り出して 外側パケットを構築し sendto を呼び出します。
Copyright
Copyright (C) CompanyName, Ltd. 2026. All rights reserved.
Definition in file potrSendThread.h.
Function Documentation
potr_send_thread_start()
int potr_send_thread_start (struct PotrContext_ * ctx) extern
Definition at line 370 of file potrSendThread.c.
References POTR_ERROR, POTR_SUCCESS, PotrContext_::send_thread, send_thread_func(), PotrContext_::send_thread_running, and PotrContext_::send_window_mutex.
Referenced by potrOpenService().
potr_send_thread_stop()
void potr_send_thread_stop (struct PotrContext_ * ctx) extern
Definition at line 397 of file potrSendThread.c.
References potr_send_queue_shutdown(), PotrContext_::send_queue, PotrContext_::send_thread, PotrContext_::send_thread_running, and PotrContext_::send_window_mutex.
Referenced by potrCloseService(), and potrOpenService().