Document of c-modernization-kit (porter): porter/libsrc/porter/api/potrSend.c File Reference
potrSend.c File Reference
potrSend 関数の実装。
#include <porter_const.h>
#include <porter.h>
#include "../potrContext.h"
#include "../infra/potrSendQueue.h"
#include "../infra/compress/compress.h"
#include "../infra/potrLog.h"
Functions
POTR_API int POTRAPI potrSend (PotrHandle handle, const void *data, size_t len, int flags)
メッセージを送信します。
Detailed Description
potrSend 関数の実装。
Author
c-modernization-kit sample team
Date
2026/03/04
Version
1.0.0
Copyright
Copyright (C) CompanyName, Ltd. 2026. All rights reserved.
Definition in file potrSend.c.
Function Documentation
potrSend()
POTR_API int POTRAPI potrSend (PotrHandle handle, const void * data, size_t len, int flags)
メッセージを送信します。
Parameters
[in] handle potrOpenService() で取得したセッションハンドル。
[in] data 送信するメッセージへのポインタ。
[in] len 送信するメッセージのバイト数。
[in] flags 送信オプションフラグ。以下のフラグを論理和で組み合わせて指定します。 0 を指定すると非圧縮・ノンブロッキング送信になります。
フラグ 説明
POTR_SEND_COMPRESS メッセージを圧縮して送信します。
POTR_SEND_BLOCKING ブロッキング送信を行います。
Returns
成功時は POTR_SUCCESS、失敗時は POTR_ERROR を返します。
通信種別に応じて以下の宛先へ UDP パケットを送信します。
通信種別 送信先
POTR_TYPE_UNICAST 接続相手の dst_port 宛にユニキャスト送信
POTR_TYPE_MULTICAST multicast_group:dst_port へ送信
POTR_TYPE_BROADCAST broadcast_addr:dst_port へ送信
compress に POTR_SEND_COMPRESS を指定した場合、内部で圧縮処理を行ってから送信します。
圧縮後のサイズが元のサイズ以上になった場合は、自動的に非圧縮で送信します。
受信側の PotrRecvCallback には、解凍済みの元メッセージが渡されます。
送受信ともにフラグメント化と組み合わせて使用できます。
ノンブロッキング送信 (flags に POTR_SEND_BLOCKING を指定しない場合)
メッセージを内部送信キューに登録して即座に返ります。
実際の sendto はバックグラウンド送信スレッドが非同期に実行します。
キューが満杯の場合は空きが生じるまで待機してからメッセージを登録し、登録後に返ります。
ブロッキング送信 (flags に POTR_SEND_BLOCKING を指定した場合)
呼び出し前に滞留しているノンブロッキング送信のメッセージが すべて sendto 完了するまで待機します。
その後、本呼び出しのメッセージをキューを通じて sendto して返ります。
本関数が返った時点で、自身のメッセージの sendto は完了しています。
Note
圧縮フォーマットには raw DEFLATE (RFC 1951) を使用します。
Linux (zlib) と Windows (Compression API MSZIP|COMPRESS_RAW) は 同一フォーマットを出力するため、クロスプラットフォーム通信に対応します。
圧縮効果がない場合 (圧縮後サイズ >= 元サイズ) は、アプリケーションへの通知なしに 内部で非圧縮に切り替えて送信します。送受信のデータ内容に影響はありません。
本関数はシングルスレッドから呼び出すことを前提としています。 複数スレッドから同時に呼び出した場合の動作は未定義です。
Warning
handle が NULL の場合は失敗を返します。
data が NULL の場合は失敗を返します。
len が 0 の場合は失敗を返します。
len が POTR_MAX_MESSAGE_SIZE を超える場合は失敗を返します。
送信スレッドが停止している場合 (potrCloseService 呼び出し後など) は失敗を返します。
Definition at line 23 of file potrSend.c.
References PotrContext_::compress_buf, PotrContext_::compress_buf_size, PotrServiceDef::encrypt_enabled, PotrContext_::global, PotrGlobalConfig::max_message_size, PotrGlobalConfig::max_payload, POTR_API, potr_compress(), POTR_CRYPTO_TAG_SIZE, POTR_ERROR, POTR_FLAG_COMPRESSED, POTR_FLAG_MORE_FRAG, POTR_LOG, POTR_LOG_ERROR, POTR_LOG_TRACE, POTR_PAYLOAD_ELEM_HDR_SIZE, POTR_SEND_BLOCKING, POTR_SEND_COMPRESS, potr_send_queue_push_wait(), potr_send_queue_wait_drained(), POTR_SUCCESS, POTRAPI, PotrContext_::send_queue, PotrContext_::send_thread_running, PotrContext_::service, and PotrServiceDef::service_id.
Referenced by main().