Document of c-modernization-kit (porter): porter/libsrc/porter/thread/potrRecvThread.h File Reference
potrRecvThread.h File Reference
受信スレッド内部ヘッダー。
#include "../potrContext.h"
Functions
int comm_recv_thread_start (struct PotrContext_ *ctx)
受信スレッドを起動します。
int comm_recv_thread_stop (struct PotrContext_ *ctx)
受信スレッドを停止します。
Detailed Description
受信スレッド内部ヘッダー。
Author
c-modernization-kit sample team
Date
2026/03/04
Version
1.0.0
Copyright
Copyright (C) CompanyName, Ltd. 2026. All rights reserved.
Definition in file potrRecvThread.h.
Function Documentation
comm_recv_thread_start()
int comm_recv_thread_start (struct PotrContext_ * ctx) extern
受信スレッドを起動します。
Parameters
[in,out] ctx セッションコンテキストへのポインタ。
Returns
成功時は POTR_SUCCESS、失敗時は POTR_ERROR を返します。
Definition at line 982 of file potrRecvThread.c.
References POTR_ERROR, POTR_LOG, POTR_LOG_DEBUG, POTR_LOG_ERROR, POTR_SUCCESS, PotrContext_::recv_thread, recv_thread_func(), PotrContext_::running, PotrContext_::service, and PotrServiceDef::service_id.
Referenced by potrOpenService().
comm_recv_thread_stop()
int comm_recv_thread_stop (struct PotrContext_ * ctx) extern
受信スレッドを停止します。
Parameters
[in,out] ctx セッションコンテキストへのポインタ。
Returns
成功時は POTR_SUCCESS、失敗時は POTR_ERROR を返します。
Definition at line 1026 of file potrRecvThread.c.
References PotrContext_::n_path, POTR_ERROR, POTR_INVALID_SOCKET, POTR_SUCCESS, PotrContext_::recv_thread, PotrContext_::running, and PotrContext_::sock.
Referenced by potrCloseService().