Document of c-modernization-kit (porter): porter/src/recv/recv.c File Reference
recv.c File Reference
受信テストコマンド。
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <porter.h>
Functions
static void sig_handler (int sig)
SIGINT シグナルハンドラー。
static void on_recv (int service_id, PotrEvent event, const void *data, size_t len)
受信コールバック関数。
static int parse_log_level (const char *str, PotrLogLevel *out)
ログレベル文字列を PotrLogLevel に変換する。
int main (int argc, char *argv[])
メインエントリーポイント。
Variables
static volatile int g_running = 1
受信ループ継続フラグ。シグナルハンドラーで 0 に設定される。
Detailed Description
受信テストコマンド。
Author
c-modernization-kit sample team
Date
2026/03/04
Version
1.1.0
指定サービスでデータを受信し続ける CLI テストコマンドです。
Ctrl+C で終了します。
使用方法
recv [-l <level>] <config_path> <service_id>
オプション
オプション 説明
-l <level> ログレベルを指定します。指定がない場合はログ出力なし。
level に指定可能な値: TRACE, DEBUG, INFO, WARN, ERROR, FATAL (大文字小文字不問)
使用例
recv porter-services.conf 10
recv -l INFO porter-services.conf 10
recv -l DEBUG porter-services.conf 10
Copyright
Copyright (C) CompanyName, Ltd. 2026. All rights reserved.
Definition in file recv.c.
Function Documentation
sig_handler()
void sig_handler (int sig) static
SIGINT シグナルハンドラー。
Parameters
[in] sig シグナル番号。
Definition at line 59 of file recv.c.
References g_running.
Referenced by main().
on_recv()
void on_recv (int service_id, PotrEvent event, const void * data, size_t len) static
受信コールバック関数。
Parameters
[in] service_id サービスの ID。
[in] event イベント種別。
[in] data 受信データへのポインタ (POTR_EVENT_DATA 時のみ有効)。
[in] len 受信データのバイト数 (POTR_EVENT_DATA 時のみ有効)。
Definition at line 75 of file recv.c.
References POTR_EVENT_CONNECTED, POTR_EVENT_DATA, POTR_EVENT_DISCONNECTED, and POTR_MAX_PAYLOAD.
Referenced by main().
parse_log_level()
int parse_log_level (const char * str, PotrLogLevel * out) static
ログレベル文字列を PotrLogLevel に変換する。
Parameters
[in] str レベル文字列 (TRACE/DEBUG/INFO/WARN/ERROR/FATAL)。
[out] out 変換結果の格納先。
Returns
変換に成功した場合は 1、未知の文字列の場合は 0 を返します。
Definition at line 116 of file recv.c.
References POTR_LOG_DEBUG, POTR_LOG_ERROR, POTR_LOG_FATAL, POTR_LOG_INFO, POTR_LOG_TRACE, and POTR_LOG_WARN.
Referenced by main().
main()
int main (int argc, char * argv[])
メインエントリーポイント。
Parameters
[in] argc コマンドライン引数の数。
[in] argv コマンドライン引数の配列。
Returns
成功時は EXIT_SUCCESS、失敗時は EXIT_FAILURE を返します。
Definition at line 157 of file recv.c.
References g_running, on_recv(), parse_log_level(), POTR_LOG_OFF, POTR_ROLE_RECEIVER, POTR_SUCCESS, potrCloseService(), potrLogConfig(), potrOpenService(), and sig_handler().
Variable Documentation
g_running
volatile int g_running = 1 static
受信ループ継続フラグ。シグナルハンドラーで 0 に設定される。
Definition at line 51 of file recv.c.
Referenced by main(), and sig_handler().