Document of c-modernization-kit (porter): porter/src/send/send.c File Reference
send.c File Reference
送信テストコマンド。
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <porter.h>
Macros
#define INPUT_BUF_SIZE (POTR_MAX_MESSAGE_SIZE + 2U)
入力バッファサイズ。POTR_MAX_MESSAGE_SIZE + 改行 + NUL。
Functions
static int parse_log_level (const char *str, PotrLogLevel *out)
ログレベル文字列を PotrLogLevel に変換する。
static int read_line (char *buf, size_t size)
標準入力から1行読み込み、末尾の改行を取り除く。
int main (int argc, char *argv[])
メインエントリーポイント。
Detailed Description
送信テストコマンド。
Author
c-modernization-kit sample team
Date
2026/03/04
Version
1.2.0
指定サービスへデータを対話式に送信する CLI テストコマンドです。
1 回のセッション内でメッセージを連続して送信できます。
各送信後に次のメッセージを送るか終了するかを選択できます。
使用方法
send [-l <level>] <config_path> <service_id>
オプション
オプション 説明
-l <level> ログレベルを指定します。指定がない場合はログ出力なし。
level に指定可能な値: TRACE, DEBUG, INFO, WARN, ERROR, FATAL (大文字小文字不問)
使用例
send porter-services.conf 10
send -l INFO porter-services.conf 10
send -l DEBUG porter-services.conf 10
Copyright
Copyright (C) CompanyName, Ltd. 2026. All rights reserved.
Definition in file send.c.
Macro Definition Documentation
INPUT_BUF_SIZE
#define INPUT_BUF_SIZE (POTR_MAX_MESSAGE_SIZE + 2U)
入力バッファサイズ。POTR_MAX_MESSAGE_SIZE + 改行 + NUL。
Definition at line 51 of file send.c.
Referenced by main().
Function Documentation
parse_log_level()
int parse_log_level (const char * str, PotrLogLevel * out) static
ログレベル文字列を PotrLogLevel に変換する。
Parameters
[in] str レベル文字列 (TRACE/DEBUG/INFO/WARN/ERROR/FATAL)。
[out] out 変換結果の格納先。
Returns
変換に成功した場合は 1、未知の文字列の場合は 0 を返します。
Definition at line 61 of file send.c.
References POTR_LOG_DEBUG, POTR_LOG_ERROR, POTR_LOG_FATAL, POTR_LOG_INFO, POTR_LOG_TRACE, and POTR_LOG_WARN.
Referenced by main().
read_line()
int read_line (char * buf, size_t size) static
標準入力から1行読み込み、末尾の改行を取り除く。
Parameters
[out] buf 読み込み先バッファ。
[in] size バッファサイズ (バイト)。
Returns
入力があれば 1、EOF またはエラーなら 0 を返します。
Definition at line 102 of file send.c.
Referenced by main().
main()
int main (int argc, char * argv[])
メインエントリーポイント。
Parameters
[in] argc コマンドライン引数の数。
[in] argv コマンドライン引数の配列。
Returns
成功時は EXIT_SUCCESS、失敗時は EXIT_FAILURE を返します。
Definition at line 120 of file send.c.
References INPUT_BUF_SIZE, parse_log_level(), POTR_LOG_OFF, POTR_ROLE_SENDER, POTR_SEND_BLOCKING, POTR_SEND_COMPRESS, POTR_SUCCESS, potrCloseService(), potrLogConfig(), potrOpenService(), potrSend(), and read_line().