Document of c-modernization-kit (porter): porter/libsrc/porter/protocol/window.h File Reference
window.h File Reference
スライディングウィンドウ管理モジュールの内部ヘッダー。
#include <stdint.h>
#include <porter_const.h>
#include <porter_type.h>
Data Structures
struct PotrWindow
スライディングウィンドウ管理構造体。
Functions
void window_init (PotrWindow *win, uint32_t initial_seq, uint16_t window_size)
ウィンドウを初期化します。
int window_send_push (PotrWindow *win, const PotrPacket *packet)
送信ウィンドウにパケットを積みます。
int window_send_ack (PotrWindow *win, uint32_t ack_num)
ACK を処理して送信ウィンドウを前進させます。
int window_send_full (const PotrWindow *win)
送信ウィンドウが満杯かどうかを返します。
int window_recv_push (PotrWindow *win, const PotrPacket *packet)
受信ウィンドウにパケットを格納します。
int window_recv_pop (PotrWindow *win, PotrPacket *packet)
受信ウィンドウから順序整列済みパケットを取り出します。
int window_recv_needs_nack (const PotrWindow *win, uint32_t *nack_num)
受信ウィンドウで欠番が発生しているか確認し、NACK 番号を返します。
Detailed Description
スライディングウィンドウ管理モジュールの内部ヘッダー。
Author
c-modernization-kit sample team
Date
2026/03/04
Version
1.0.0
Copyright
Copyright (C) CompanyName, Ltd. 2026. All rights reserved.
Definition in file window.h.
Function Documentation
window_init()
void window_init (PotrWindow * win, uint32_t initial_seq, uint16_t window_size) extern
ウィンドウを初期化します。
Parameters
[out] win 初期化するウィンドウ構造体へのポインタ。
[in] initial_seq 初期通番。
[in] window_size ウィンドウサイズ (パケット数)。
Definition at line 29 of file window.c.
References PotrWindow::base_seq, PotrWindow::next_seq, POTR_MAX_WINDOW_SIZE, and PotrWindow::window_size.
Referenced by potrOpenService().
window_send_push()
int window_send_push (PotrWindow * win, const PotrPacket * packet) extern
送信ウィンドウにパケットを積みます。
Parameters
[in,out] win 送信ウィンドウ構造体へのポインタ。
[in] packet 積むパケットへのポインタ。
Returns
成功時は POTR_SUCCESS、ウィンドウ満杯の場合は POTR_ERROR を返します。
Definition at line 60 of file window.c.
References PotrWindow::next_seq, PotrWindow::packets, POTR_ERROR, POTR_SUCCESS, PotrWindow::valid, win_index(), and window_send_full().
Referenced by potrSend().
window_send_ack()
int window_send_ack (PotrWindow * win, uint32_t ack_num) extern
ACK を処理して送信ウィンドウを前進させます。
Parameters
[in,out] win 送信ウィンドウ構造体へのポインタ。
[in] ack_num 確認応答された通番。
Returns
成功時は POTR_SUCCESS、失敗時は POTR_ERROR を返します。
Definition at line 90 of file window.c.
References PotrWindow::base_seq, POTR_ERROR, POTR_SUCCESS, seqnum_in_window(), PotrWindow::valid, and win_index().
Referenced by recv_thread_func().
window_send_full()
int window_send_full (const PotrWindow * win) extern
送信ウィンドウが満杯かどうかを返します。
Parameters
[in] win 送信ウィンドウ構造体へのポインタ。
Returns
満杯の場合は 1、空きがある場合は 0 を返します。
Definition at line 118 of file window.c.
References PotrWindow::base_seq, PotrWindow::next_seq, and PotrWindow::window_size.
Referenced by potrSend(), and window_send_push().
window_recv_push()
int window_recv_push (PotrWindow * win, const PotrPacket * packet) extern
受信ウィンドウにパケットを格納します。
Parameters
[in,out] win 受信ウィンドウ構造体へのポインタ。
[in] packet 格納するパケットへのポインタ。
Returns
成功時は POTR_SUCCESS、ウィンドウ外の場合は POTR_ERROR を返します。
通番が受信ウィンドウ内であればバッファリングします。
追い越し (順序外到着) にも対応します。
Definition at line 141 of file window.c.
References PotrWindow::base_seq, PotrWindow::packets, POTR_ERROR, POTR_SUCCESS, PotrPacket::seq_num, seqnum_in_window(), PotrWindow::valid, win_index(), and PotrWindow::window_size.
Referenced by recv_thread_func().
window_recv_pop()
int window_recv_pop (PotrWindow * win, PotrPacket * packet) extern
受信ウィンドウから順序整列済みパケットを取り出します。
Parameters
[in,out] win 受信ウィンドウ構造体へのポインタ。
[out] packet 取り出したパケットを格納する構造体へのポインタ。
Returns
取り出せた場合は POTR_SUCCESS、次のパケットが未着の場合は POTR_ERROR を返します。
Definition at line 170 of file window.c.
References PotrWindow::base_seq, PotrWindow::next_seq, PotrWindow::packets, POTR_ERROR, POTR_SUCCESS, PotrWindow::valid, and win_index().
Referenced by recv_thread_func().
window_recv_needs_nack()
int window_recv_needs_nack (const PotrWindow * win, uint32_t * nack_num) extern
受信ウィンドウで欠番が発生しているか確認し、NACK 番号を返します。
Parameters
[in] win 受信ウィンドウ構造体へのポインタ。
[out] nack_num 欠番の通番を格納するポインタ。
Returns
欠番がある場合は 1、ない場合は 0 を返します。
Definition at line 201 of file window.c.
References PotrWindow::next_seq, PotrWindow::valid, and win_index().
Referenced by recv_thread_func().